<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Approaches to Bayesian Computation | Spatio-Temporal Methods in Environmental Epidemiology with R. Second Edition</title>
  <meta name="description" content="Chapter 6 Approaches to Bayesian Computation | Spatio-Temporal Methods in Environmental Epidemiology with R. Second Edition" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Approaches to Bayesian Computation | Spatio-Temporal Methods in Environmental Epidemiology with R. Second Edition" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/img/cover.jpg" />
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Approaches to Bayesian Computation | Spatio-Temporal Methods in Environmental Epidemiology with R. Second Edition" />
  
  
  <meta name="twitter:image" content="/img/cover.jpg" />

<meta name="author" content="Gavin Shaddick, James V. Zidek, and Alexandra M. Schmidt" />


<meta name="date" content="2023-08-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="embracing.html"/>
<link rel="next" href="Strategies.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatio-temporal methods in environmental epidemiology</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="preface-to-second-edition.html"><a href="preface-to-second-edition.html"><i class="fa fa-check"></i>PREFACE TO SECOND EDITION</a></li>
<li class="chapter" data-level="1" data-path="why.html"><a href="why.html"><i class="fa fa-check"></i><b>1</b> An overview of spatio-temporal epidemiology and knowledge discovery?</a></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> An introduction to modelling health risks and impacts</a>
<ul>
<li class="chapter" data-level="" data-path="basics.html"><a href="basics.html#example-2.7-estimating-the-smr-using-a-poisson-glm"><i class="fa fa-check"></i>Example 2.7: Estimating the SMR using a Poisson GLM</a></li>
<li class="chapter" data-level="" data-path="basics.html"><a href="basics.html#example-2.8-estimating-the-smr-using-quasi-likelihood"><i class="fa fa-check"></i>Example 2.8: Estimating the SMR using quasi-likelihood</a></li>
<li class="chapter" data-level="" data-path="basics.html"><a href="basics.html#example-2.9-modelling-differences-in-smrs-in-relation-to-differences-in-exposures"><i class="fa fa-check"></i>Example 2.9: Modelling differences in SMRs in relation to differences in exposures</a></li>
<li class="chapter" data-level="" data-path="basics.html"><a href="basics.html#example-2.10-modelling-the-risks-associated-with-lagged-effects-of-air-pollution"><i class="fa fa-check"></i>Example 2.10: Modelling the risks associated with lagged effects of air pollution</a></li>
<li class="chapter" data-level="" data-path="basics.html"><a href="basics.html#example-2.10-estimating-the-odds-ratio-in-a-case-control-study-using-a-logistic-model"><i class="fa fa-check"></i>Example 2.10: Estimating the odds ratio in a case-control study using a logistic model</a></li>
<li class="chapter" data-level="" data-path="basics.html"><a href="basics.html#example-2.11-estimating-the-odds-ratio-of-asthma-associated-with-proximity-to-roads"><i class="fa fa-check"></i>Example 2.11: Estimating the odds ratio of asthma associated with proximity to roads</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>3</b> The importance of uncertainty: assessment and quantification</a>
<ul>
<li class="chapter" data-level="" data-path="uncertainty.html"><a href="uncertainty.html#supplementary-material"><i class="fa fa-check"></i>Supplementary Material</a>
<ul>
<li class="chapter" data-level="" data-path="uncertainty.html"><a href="uncertainty.html#more-on-qualitative-uncertainty"><i class="fa fa-check"></i>More on qualitative uncertainty</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>4</b> Extracting information from data</a>
<ul>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#getting-to-know-the-structure-of-dataframes"><i class="fa fa-check"></i>Getting to know the structure of dataframes</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#extracting-and-creating-variables"><i class="fa fa-check"></i>Extracting and creating variables</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#simple-manipulations-using-tidyverse"><i class="fa fa-check"></i>Simple manipulations using Tidyverse</a>
<ul>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#filter-rows-in-tidyverse"><i class="fa fa-check"></i>Filter rows in Tidyverse</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#sorting-rows-in-tidyverse"><i class="fa fa-check"></i>Sorting rows in Tidyverse</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#select-columns-in-tidyverse"><i class="fa fa-check"></i>Select columns in Tidyverse</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#adding-columns"><i class="fa fa-check"></i>Adding columns</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#pipes"><i class="fa fa-check"></i>Pipes</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#chaining-pipes"><i class="fa fa-check"></i>Chaining pipes</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#grouping-and-summarizing"><i class="fa fa-check"></i>Grouping and summarizing</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#example-4.1-health-impacts-associated-with-outdoor-air-pollution"><i class="fa fa-check"></i>Example 4.1: Health impacts associated with outdoor air pollution</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#example-4.3.-mapping-cancer-incidence-in-southern-and-eastern-serbia"><i class="fa fa-check"></i>Example 4.3. Mapping cancer incidence in Southern and Eastern Serbia</a>
<ul>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#creating-maps-of-southern-and-eastern-serbia"><i class="fa fa-check"></i>Creating maps of Southern and Eastern Serbia</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#example-4.4-cancer-in-bor"><i class="fa fa-check"></i>Example 4.4 Cancer in Bor</a></li>
<li class="chapter" data-level="" data-path="data.html"><a href="data.html#calculating-smrs"><i class="fa fa-check"></i>Calculating SMRs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="embracing.html"><a href="embracing.html"><i class="fa fa-check"></i><b>5</b> Embracing uncertainty: the Bayesian approach</a></li>
<li class="chapter" data-level="6" data-path="computation.html"><a href="computation.html"><i class="fa fa-check"></i><b>6</b> Approaches to Bayesian Computation</a>
<ul>
<li class="chapter" data-level="" data-path="computation.html"><a href="computation.html#example-6.2-gibbs-sampling-with-a-poisson-gamma-model---hospital-admissions-for-chronic-obstructive-pulmonary-disease-copd-for-england-between-2001-2010"><i class="fa fa-check"></i>Example 6.2: Gibbs sampling with a Poisson-Gamma model - hospital admissions for chronic obstructive pulmonary disease (COPD) for England between 2001-2010</a>
<ul>
<li class="chapter" data-level="" data-path="computation.html"><a href="computation.html#modelling-the-raw-standardized-mortality-rates-smrs"><i class="fa fa-check"></i>Modelling the raw standardized mortality rates (SMRs)</a></li>
<li class="chapter" data-level="" data-path="computation.html"><a href="computation.html#mcmc-implementation-of-the-poisson-gamma-model-in-r"><i class="fa fa-check"></i>MCMC implementation of the Poisson-Gamma model in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="computation.html"><a href="computation.html#code-for-the-poisson-gamma-model-in-nimble"><i class="fa fa-check"></i>Code for the Poisson-Gamma model in Nimble</a></li>
<li class="chapter" data-level="" data-path="computation.html"><a href="computation.html#example-6.3-fitting-a-poisson-regression-model"><i class="fa fa-check"></i>Example 6.3: Fitting a Poisson regression model</a>
<ul>
<li class="chapter" data-level="" data-path="computation.html"><a href="computation.html#nimble"><i class="fa fa-check"></i>Nimble</a></li>
<li class="chapter" data-level="" data-path="computation.html"><a href="computation.html#stan"><i class="fa fa-check"></i>Stan</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Strategies.html"><a href="Strategies.html"><i class="fa fa-check"></i><b>7</b> Strategies for modelling</a>
<ul>
<li class="chapter" data-level="" data-path="Strategies.html"><a href="Strategies.html#example-7.6-variable-selection-in-land-use-regression-using-lasso-and-horseshoe-priors"><i class="fa fa-check"></i>Example 7.6 Variable selection in land use regression using lasso and horseshoe priors</a>
<ul>
<li class="chapter" data-level="" data-path="Strategies.html"><a href="Strategies.html#nimble-1"><i class="fa fa-check"></i>Nimble</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="trusted.html"><a href="trusted.html"><i class="fa fa-check"></i><b>8</b> The challenges of working with real-world data</a>
<ul>
<li class="chapter" data-level="" data-path="trusted.html"><a href="trusted.html#solutions-to-selected-exercises"><i class="fa fa-check"></i>Solutions to Selected Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="trusted.html"><a href="trusted.html#placeholder-repeat-the-black-smoke-analysis-conducted-in-watson-et-al.-2019.-in-the-naive-model."><i class="fa fa-check"></i>PLACEHOLDER: Repeat the Black Smoke analysis conducted in Watson et al. 2019. in the “naive” model.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="Disease.html"><a href="Disease.html"><i class="fa fa-check"></i><b>9</b> Disease-spatial patterns</a>
<ul>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#example-9.1-empirical-bayes-and-bayes-smoothing-of-copd-mortality-for-2010"><i class="fa fa-check"></i>Example 9.1: Empirical Bayes and Bayes smoothing of COPD mortality for 2010</a>
<ul>
<li class="chapter" data-level="9.0.1" data-path="Disease.html"><a href="Disease.html#empirical-bayes-estimate-using-spatialepi"><i class="fa fa-check"></i><b>9.0.1</b> Empirical Bayes estimate using <code>SpatialEpi</code></a></li>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#nimble-2"><i class="fa fa-check"></i>Nimble</a></li>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#stan-1"><i class="fa fa-check"></i>Stan</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#example-9.3-fitting-a-conditional-spatial-model-in-nimble-and-rstan"><i class="fa fa-check"></i>Example 9.3: Fitting a conditional spatial model in <code>NIMBLE</code> and <code>RStan</code></a>
<ul>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#nimble-3"><i class="fa fa-check"></i>Nimble</a></li>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#stan-2"><i class="fa fa-check"></i>Stan</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#example-9.4-fitting-a-conditional-spatial-model-using-carbayes"><i class="fa fa-check"></i>Example 9.4: Fitting a conditional spatial model using CARBayes</a></li>
<li class="chapter" data-level="" data-path="Disease.html"><a href="Disease.html#example-9.5-fitting-a-conditional-model-using-inla"><i class="fa fa-check"></i>Example 9.5: Fitting a conditional model using INLA</a></li>
<li class="chapter" data-level="9.1" data-path="Disease.html"><a href="Disease.html#supplementary-example-fitting-a-leroux-model-to-the-copd-dataset-using-nimble-stan-and-carbayes"><i class="fa fa-check"></i><b>9.1</b> Supplementary Example: Fitting a Leroux model to the COPD dataset using Nimble, Stan and CARBayes</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="hazards.html"><a href="hazards.html"><i class="fa fa-check"></i><b>10</b> Environmental hazards-spatial models</a>
<ul>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.1-spatial-patterns-in-lead-concentrations-in-the-soil-of-the-meuse-river-flood-plain"><i class="fa fa-check"></i>Example 10.1 Spatial patterns in lead concentrations in the soil of the Meuse River flood plain</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.2-examining-the-log-concentrations-of-lead-in-the-meuse-river-flood-plain"><i class="fa fa-check"></i>Example 10.2: Examining the log concentrations of lead in the Meuse River flood plain</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.3-mapping-the-locations-of-ozone-monitoring-sites-in-new-york-state"><i class="fa fa-check"></i>Example 10.3: Mapping the locations of ozone monitoring sites in New York State</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.5-spatial-prediction-of-temperatures-in-california"><i class="fa fa-check"></i>Example 10.5: Spatial prediction of temperatures in California</a></li>
<li class="chapter" data-level="10.1" data-path="hazards.html"><a href="hazards.html#example-10.6-fitting-a-bayesian-exponential-spatial-model-using-nimble"><i class="fa fa-check"></i><b>10.1</b> Example 10.6 Fitting a Bayesian exponential spatial model using NIMBLE</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.7-spatial-prediction-of-pm_2.5-in-europe"><i class="fa fa-check"></i>Example 10.7 Spatial prediction of <span class="math inline">\(PM_{2.5}\)</span> in Europe</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.10-creating-a-mesh-black-smoke-monitoring-locations-in-the-uk"><i class="fa fa-check"></i>Example 10.10 Creating a mesh: black smoke monitoring locations in the UK</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.12-plotting-directional-variograms-for-temperatures-in-california"><i class="fa fa-check"></i>Example 10.12 Plotting directional variograms for temperatures in California</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-10.14-spatial-modeling-of-malaria-in-gambia"><i class="fa fa-check"></i>Example 10.14: Spatial modeling of malaria in Gambia</a>
<ul>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#nimble-4"><i class="fa fa-check"></i>Nimble</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#stan-3"><i class="fa fa-check"></i>Stan</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#supplementary-material-1"><i class="fa fa-check"></i>Supplementary Material</a>
<ul>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#example-analysis-of-benzene-concentrations-across-montreal-qc-canada"><i class="fa fa-check"></i>Example: Analysis of benzene concentrations across Montreal, QC, Canada</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.2-examining-the-log-concentrations-of-benzene-in-montreal"><i class="fa fa-check"></i>Extra 10.2: Examining the log concentrations of benzene in Montreal</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.5-variogram"><i class="fa fa-check"></i>Extra 10.5: Variogram</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.6-basic-spatial-modelling-and-prediction-of-benzene-in-montreal"><i class="fa fa-check"></i>Extra 10.6 Basic spatial modelling and prediction of benzene in Montreal</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.8-spatial-modelling-of-benzene-in-montreal"><i class="fa fa-check"></i>Extra 10.8 Spatial modelling of Benzene in Montreal</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.9-spatial-predictions"><i class="fa fa-check"></i>Extra 10.9: Spatial predictions</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.10-inla-creating-a-mesh"><i class="fa fa-check"></i>Extra 10.10: INLA, creating a mesh</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.12-fitting-an-spde-model-using-rinla-benzene-concentration-in-montreal"><i class="fa fa-check"></i>Extra 10.12: Fitting an SPDE model using R–INLA: benzene concentration in Montreal</a></li>
<li class="chapter" data-level="" data-path="hazards.html"><a href="hazards.html#extra-10.13-directional-variograms"><i class="fa fa-check"></i>Extra 10.13: Directional variograms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Time.html"><a href="Time.html"><i class="fa fa-check"></i><b>11</b> Modelling temporal data: time series analysis and forecasting</a>
<ul>
<li class="chapter" data-level="" data-path="Time.html"><a href="Time.html#example-11.1-ground-level-ozone-concentrations"><i class="fa fa-check"></i>Example 11.1 Ground level ozone concentrations</a></li>
<li class="chapter" data-level="" data-path="Time.html"><a href="Time.html#example-11.2-low-pass-filtering-of-ozone-levels-using-the-moving-average"><i class="fa fa-check"></i>Example 11.2 Low-pass filtering of ozone levels using the moving average</a></li>
<li class="chapter" data-level="" data-path="Time.html"><a href="Time.html#example-11.12-forecasting-ozone-levels"><i class="fa fa-check"></i>Example 11.12 Forecasting ozone levels</a></li>
<li class="chapter" data-level="" data-path="Time.html"><a href="Time.html#example-11.13-forecasting-volcanic-ash"><i class="fa fa-check"></i>Example 11.13 Forecasting volcanic ash</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="exposure.html"><a href="exposure.html"><i class="fa fa-check"></i><b>12</b> Exposure assessment-over space and time</a>
<ul>
<li class="chapter" data-level="" data-path="exposure.html"><a href="exposure.html#example-idk-spatio-temporal-model-for-the-uk-ozone-data"><i class="fa fa-check"></i>Example IDK: Spatio-temporal model for the UK ozone data</a>
<ul>
<li class="chapter" data-level="" data-path="exposure.html"><a href="exposure.html#nimble-7"><i class="fa fa-check"></i>Nimble</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="causality.html"><a href="causality.html"><i class="fa fa-check"></i><b>13</b> Causality-roadblocks on the way to it</a>
<ul>
<li class="chapter" data-level="" data-path="causality.html"><a href="causality.html#solutions-to-selected-exercises-1"><i class="fa fa-check"></i>Solutions to Selected Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="causality.html"><a href="causality.html#question-13.16-load-the-italy-and-china-data-described-in-example-13.3-and-included-in-the-supplementary-bookdown-material-into-r."><i class="fa fa-check"></i>Question 13.16: Load the Italy and China data, described in Example 13.3, and included in the supplementary Bookdown material into R.</a></li>
<li class="chapter" data-level="" data-path="causality.html"><a href="causality.html#question-13.17-using-the-italy-and-china-data-stratified-by-the-age-groups-70-and-geq-70-obtain-empirical-estimates-of-p_1-and-p_2-as-defined-in-an-sdis.-in-the-following-questions-assume-that-p_1-and-p_2-are-the-population-values."><i class="fa fa-check"></i>Question 13.17: Using the Italy and China data stratified by the age groups <span class="math inline">\(&lt;70\)</span> and <span class="math inline">\(\geq 70\)</span>, obtain empirical estimates of <span class="math inline">\(P_1\)</span> and <span class="math inline">\(P_2\)</span>, as defined in an SDis. In the following questions, assume that <span class="math inline">\(P_1\)</span> and <span class="math inline">\(P_2\)</span> are the population values.</a></li>
<li class="chapter" data-level="" data-path="causality.html"><a href="causality.html#question-13.18-stratify-the-italy-and-china-data-by-the-age-groups-50-and-geq-50.-display-the-corresponding-contingency-tables."><i class="fa fa-check"></i>Question 13.18: Stratify the Italy and China data by the age groups <span class="math inline">\(&lt;50\)</span> and <span class="math inline">\(\geq 50\)</span>. Display the corresponding contingency tables.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="monitoring.html"><a href="monitoring.html"><i class="fa fa-check"></i><b>14</b> Better monitoring network design-getting better measurements</a></li>
<li class="chapter" data-level="15" data-path="frontiers.html"><a href="frontiers.html"><i class="fa fa-check"></i><b>15</b> Current frontiers</a></li>
<li class="chapter" data-level="" data-path="course.html"><a href="course.html"><i class="fa fa-check"></i>Course</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatio-Temporal Methods in Environmental Epidemiology with R. Second Edition</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="computation" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Approaches to Bayesian Computation<a href="computation.html#computation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter describes methods for implementing Bayesian models when their complexity means that simple, analytic solutions may not be available. The reader will have gained an understanding of the following topics:</p>
<ul>
<li><p>analytical approximations to the posterior distribution;</p></li>
<li><p>use of samples from a posterior distribution for inference and Monte Carlo integration;</p></li>
<li><p>methods for direct sampling such as importance and rejection sampling;</p></li>
<li><p>Markov Chain Monte Carlo (MCMC) and methods for obtaining samples from the required posterior distribution including Metropolis–Hastings and Gibbs algorithms;</p></li>
<li><p>use of NIMBLE and RStan packages to fit Bayesian models using Gibbs sampling;</p></li>
<li><p>Integrated Nested Laplace Approximations (INLA) as a method for performing efficient Bayesian inference including the use of R-INLA to implement a wide variety of latent Gaussian models.</p></li>
</ul>
<div id="example-6.2-gibbs-sampling-with-a-poisson-gamma-model---hospital-admissions-for-chronic-obstructive-pulmonary-disease-copd-for-england-between-2001-2010" class="section level2 unnumbered hasAnchor">
<h2>Example 6.2: Gibbs sampling with a Poisson-Gamma model - hospital admissions for chronic obstructive pulmonary disease (COPD) for England between 2001-2010<a href="computation.html#example-6.2-gibbs-sampling-with-a-poisson-gamma-model---hospital-admissions-for-chronic-obstructive-pulmonary-disease-copd-for-england-between-2001-2010" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We now look at example into the hospital admission rates for chronic obstructive pulmonary disease (COPD) in England between 2001–2010.</p>
<p>In England, there are 324 local authority administrative areas each with an observed and expected number of cases. The expected numbers were calculated using indirect standardization by applying the age–sex specific rates for the whole of England to the age–sex population profile of each of
the areas.</p>
<p>We show the full conditional distributions for a Poisson model where the prior distribution on the rates is Gamma, that is, <span class="math inline">\(y_i \mid \theta_, E_i \sim Poi(\theta_i E_i)\)</span> where <span class="math inline">\(E_i\)</span> is the expected number of cases in area <span class="math inline">\(i\)</span>. In particular, let <span class="math inline">\(\mathbf{y} = (y_1, ..., y_N)\)</span> be a <span class="math inline">\(N\)</span>-dimensional vector with observed counts on the total number of
hospital admissions for chronic obstructive pulmonary disease (COPD) for England between 2001 and 2010. The expected numbers of hospital admissions by local authority were computed as described in Chapter 2, Section 2.1.</p>
<p>If we assign a Gamma prior to the random effects <span class="math inline">\(\theta_i\)</span>, i.e., <span class="math inline">\(\theta_i \sim Gamma(a, b)\)</span> for <span class="math inline">\(i=1, \dots N\)</span>, and independent exponential distributions to the hyperparameters <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> then we can find the full conditional distributions required for Gibbs sampling.</p>
<p>The joint posterior is proportional to</p>
<p><span class="math display">\[\begin{eqnarray} \nonumber
p(a, b, \mathbf{\theta} | \mathbf{y}) &amp;\propto&amp; \prod^N _{i=1} \frac{\left(\theta_i E_i\right)^{y_i}}{y_i!} \exp(-\theta_i E_i) \, \frac{b^{a}}{\Gamma (a) }\theta_i^{a-1} e^{-b \theta_i}  \\ \nonumber
&amp;&amp; \times \lambda_{a} \exp(-\lambda_{a}) \, \lambda_{b}\exp(-\lambda_{b}),
\end{eqnarray}\]</span>
and the full conditionals are:</p>
<ul>
<li>Posterior full conditional for each <span class="math inline">\(\theta_i\)</span>, <span class="math inline">\(i=1,\dots,N\)</span>:
<span class="math display">\[\begin{eqnarray}
p(\theta_i | \mathbf{\theta}_{-i}, a, b, \mathbf{y}) \propto  \theta_i^{y_i+a-1} \exp[-(E_i+b)\theta_i],
\end{eqnarray}\]</span>
which is the kernel of a Gamma distribution with parameters <span class="math inline">\(y_i+a\)</span> and <span class="math inline">\(E_i+b\)</span>;</li>
<li>Posterior full conditional for <span class="math inline">\(b\)</span>:
<span class="math display">\[\begin{eqnarray}
p(b | \mathbf{\theta}, a, \mathbf{y}) \propto
  b^{N a} \exp\left[-\left(\sum^N_{i=1}\theta_i + \lambda_{b}\right)b\right],
\end{eqnarray}\]</span>
which is the kernel of a Gamma distribution with parameters <span class="math inline">\(Na+1\)</span> and <span class="math inline">\((\sum^N_{i=1}\theta_i + \lambda_{b})\)</span>;</li>
<li>Posterior full conditional for <span class="math inline">\(a\)</span>:
<span class="math display">\[\begin{eqnarray}
p(a | \mathbf{\theta}, b, \mathbf{y})  \propto  \frac{\left(b^N \prod^N_{i=1}\theta_i\right)^{a-1}}{\Gamma (a)^N },
\end{eqnarray}\]</span>
which does not have a closed form. We propose to sample from <span class="math inline">\(p(a | \mathbf{\theta}, b, \mathbf{y})\)</span> through a random walk, Metropolis-Hastings step. As <span class="math inline">\(a\)</span> must be strictly positive, the proposal is a log-normal distribution whose associated normal distribution has mean at the logarithm of the current value and some fixed variance, say <span class="math inline">\(u\)</span>, that needs to be tuned.</li>
</ul>
<p>For this example, the following packages are needed <code>ggplot2</code> and <code>sf</code>.</p>
<p>Load the necessary packages.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="computation.html#cb114-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb114-2"><a href="computation.html#cb114-2" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div>
<p>To create SMR maps, we need to load the relevant shapefiles into the <code>R</code> session.</p>
<ul>
<li><a href="https://github.com/spacetime-environ/stepi2/blob/main/data/copd/englandlocalauthority.shp">englandlocalauthority.shp</a> and <a href="https://github.com/spacetime-environ/stepi2/blob/main/data/copd/englandlocalauthority.dbf">englandlocalauthority.dbf</a> contain the location, shape, and attributes of English local authorities. The function <code>read_sf()</code> from the <code>sf</code> package will read these shapefiles into <code>R</code>.</li>
<li><a href="https://github.com/spacetime-environ/stepi2/blob/main/data/copd/copdmortalityobserved.csv">copdmortalityobserved.csv</a> contains the <strong>observed</strong> number of hospital admissions in England by local authority. You can find this data by clicking.</li>
<li><a href="https://github.com/spacetime-environ/stepi2/blob/main/data/copd/copdmortalityexpected.csv">copdmortalityexpected.csv</a> contains the <strong>expected</strong> number of hospital admissions in England by local authority.</li>
</ul>
<div class="sourceCode" id="cb115"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb115-1"><a href="computation.html#cb115-1" tabindex="-1"></a><span class="co"># Reading in the borders of the shape file</span></span>
<span id="cb115-2"><a href="computation.html#cb115-2" tabindex="-1"></a>england <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">&quot;data/copd/englandlocalauthority.shp&quot;</span>)</span>
<span id="cb115-3"><a href="computation.html#cb115-3" tabindex="-1"></a><span class="co"># Reading the data</span></span>
<span id="cb115-4"><a href="computation.html#cb115-4" tabindex="-1"></a>observed <span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;data/copd/copdmortalityobserved.csv&quot;</span>, <span class="at">row.names =</span> <span class="dv">1</span>)</span>
<span id="cb115-5"><a href="computation.html#cb115-5" tabindex="-1"></a>expected <span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;data/copd/copdmortalityexpected.csv&quot;</span>, <span class="at">row.names =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Print summaries of the observed and expected counts.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb116-1"><a href="computation.html#cb116-1" tabindex="-1"></a><span class="co"># Printing first six rows of the observed counts</span></span>
<span id="cb116-2"><a href="computation.html#cb116-2" tabindex="-1"></a><span class="fu">head</span>(observed)</span></code></pre></div>
<pre><code>##                         name Y2001 Y2002 Y2003 Y2004 Y2005 Y2006 Y2007 Y2008
## 00AA      City of London LB      2     0     3     1     1     1     5     1
## 00AB Barking and Dagenham LB   100   100   122    93   136    97    91    96
## 00AC               Barnet LB   110   102   106    89    99    97    72    84
## 00AD               Bexley LB   109   113   113    96   113    97    94    89
## 00AE                Brent LB    69    89    70    59    61    48    53    46
## 00AF              Bromley LB   120   129   135   124   128   117   120   106
##      Y2009 Y2010
## 00AA     0     1
## 00AB   101    78
## 00AC    78    89
## 00AD    93    93
## 00AE    55    43
## 00AF   107   113</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb118-1"><a href="computation.html#cb118-1" tabindex="-1"></a><span class="co"># Printing first six rows of the expected counts</span></span>
<span id="cb118-2"><a href="computation.html#cb118-2" tabindex="-1"></a><span class="fu">head</span>(expected)</span></code></pre></div>
<pre><code>##           E2001     E2002      E2003      E2004      E2005      E2006
## 00AA   2.648915   2.68106   2.727112   2.749562   2.808655   2.915977
## 00AB  63.946730  63.41700  62.567863  61.444884  60.677119  59.678672
## 00AC 121.795213 121.91534 122.451050 123.201898 124.449563 125.982868
## 00AD  90.201336  91.24645  91.949050  92.754781  93.674540  94.598593
## 00AE  76.876437  77.18529  78.017980  78.967493  80.422828  81.785325
## 00AF 131.182934 132.30521 133.257442 134.520920 136.441229 137.382528
##           E2007      E2008      E2009      E2010
## 00AA   3.021586   3.114696   3.237998   3.237998
## 00AB  58.487583  57.701932  57.250524  57.250524
## 00AC 127.088805 128.825149 131.374946 131.374946
## 00AD  95.447131  96.832061  97.651369  97.651369
## 00AE  83.651266  85.265264  87.089119  87.089119
## 00AF 138.634021 139.508507 140.634084 140.634084</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb120-1"><a href="computation.html#cb120-1" tabindex="-1"></a><span class="co"># Summarising the observed counts</span></span>
<span id="cb120-2"><a href="computation.html#cb120-2" tabindex="-1"></a><span class="fu">summary</span>(observed)</span></code></pre></div>
<pre><code>##      name               Y2001            Y2002            Y2003       
##  Length:324         Min.   :  2.00   Min.   :  0.00   Min.   :  3.00  
##  Class :character   1st Qu.: 35.00   1st Qu.: 38.00   1st Qu.: 38.00  
##  Mode  :character   Median : 50.00   Median : 52.00   Median : 52.00  
##                     Mean   : 68.01   Mean   : 69.63   Mean   : 73.44  
##                     3rd Qu.: 83.50   3rd Qu.: 80.75   3rd Qu.: 83.25  
##                     Max.   :445.00   Max.   :438.00   Max.   :480.00  
##      Y2004            Y2005            Y2006            Y2007       
##  Min.   :  1.00   Min.   :  1.00   Min.   :  1.00   Min.   :  5.00  
##  1st Qu.: 35.00   1st Qu.: 37.00   1st Qu.: 35.00   1st Qu.: 37.00  
##  Median : 49.50   Median : 51.00   Median : 49.00   Median : 50.00  
##  Mean   : 66.67   Mean   : 69.37   Mean   : 67.07   Mean   : 68.17  
##  3rd Qu.: 81.25   3rd Qu.: 80.50   3rd Qu.: 81.00   3rd Qu.: 79.00  
##  Max.   :428.00   Max.   :395.00   Max.   :428.00   Max.   :456.00  
##      Y2008            Y2009            Y2010       
##  Min.   :  1.00   Min.   :  0.00   Min.   :  1.00  
##  1st Qu.: 37.00   1st Qu.: 36.00   1st Qu.: 38.00  
##  Median : 51.00   Median : 50.00   Median : 51.00  
##  Mean   : 71.40   Mean   : 67.04   Mean   : 68.81  
##  3rd Qu.: 84.25   3rd Qu.: 78.00   3rd Qu.: 81.25  
##  Max.   :463.00   Max.   :394.00   Max.   :441.00</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb122-1"><a href="computation.html#cb122-1" tabindex="-1"></a><span class="co"># Summarising the expected counts</span></span>
<span id="cb122-2"><a href="computation.html#cb122-2" tabindex="-1"></a><span class="fu">summary</span>(expected)</span></code></pre></div>
<pre><code>##      E2001             E2002             E2003             E2004       
##  Min.   :  2.649   Min.   :  2.681   Min.   :  2.727   Min.   :  2.75  
##  1st Qu.: 39.066   1st Qu.: 39.456   1st Qu.: 39.849   1st Qu.: 40.60  
##  Median : 51.766   Median : 52.671   Median : 53.487   Median : 54.29  
##  Mean   : 62.944   Mean   : 63.589   Mean   : 64.139   Mean   : 64.72  
##  3rd Qu.: 74.292   3rd Qu.: 74.974   3rd Qu.: 74.701   3rd Qu.: 74.02  
##  Max.   :370.913   Max.   :371.271   Max.   :369.861   Max.   :368.87  
##      E2005             E2006             E2007             E2008        
##  Min.   :  2.809   Min.   :  2.916   Min.   :  3.022   Min.   :  3.115  
##  1st Qu.: 41.646   1st Qu.: 42.497   1st Qu.: 43.203   1st Qu.: 44.262  
##  Median : 54.765   Median : 55.506   Median : 56.552   Median : 57.522  
##  Mean   : 65.440   Mean   : 66.180   Mean   : 67.022   Mean   : 67.950  
##  3rd Qu.: 75.003   3rd Qu.: 75.260   3rd Qu.: 75.790   3rd Qu.: 76.935  
##  Max.   :368.565   Max.   :367.838   Max.   :368.026   Max.   :368.291  
##      E2009             E2010        
##  Min.   :  3.238   Min.   :  3.238  
##  1st Qu.: 45.062   1st Qu.: 45.062  
##  Median : 58.077   Median : 58.077  
##  Mean   : 68.901   Mean   : 68.901  
##  3rd Qu.: 78.166   3rd Qu.: 78.166  
##  Max.   :368.940   Max.   :368.940</code></pre>
<div id="modelling-the-raw-standardized-mortality-rates-smrs" class="section level3 unnumbered hasAnchor">
<h3>Modelling the raw standardized mortality rates (SMRs)<a href="computation.html#modelling-the-raw-standardized-mortality-rates-smrs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Calculate the raw SMRs as</p>
<p><span class="math display">\[ \text{SMR} = \frac{observed}{expected}\]</span></p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="computation.html#cb124-1" tabindex="-1"></a>SMR_raw <span class="ot">&lt;-</span> observed[, <span class="sc">-</span><span class="dv">1</span>] <span class="sc">/</span> expected</span>
<span id="cb124-2"><a href="computation.html#cb124-2" tabindex="-1"></a></span>
<span id="cb124-3"><a href="computation.html#cb124-3" tabindex="-1"></a><span class="co"># Rename columns</span></span>
<span id="cb124-4"><a href="computation.html#cb124-4" tabindex="-1"></a><span class="fu">names</span>(SMR_raw) <span class="ot">&lt;-</span></span>
<span id="cb124-5"><a href="computation.html#cb124-5" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;SMR2001&quot;</span>,</span>
<span id="cb124-6"><a href="computation.html#cb124-6" tabindex="-1"></a>    <span class="st">&quot;SMR2002&quot;</span>,</span>
<span id="cb124-7"><a href="computation.html#cb124-7" tabindex="-1"></a>    <span class="st">&quot;SMR2003&quot;</span>,</span>
<span id="cb124-8"><a href="computation.html#cb124-8" tabindex="-1"></a>    <span class="st">&quot;SMR2004&quot;</span>,</span>
<span id="cb124-9"><a href="computation.html#cb124-9" tabindex="-1"></a>    <span class="st">&quot;SMR2005&quot;</span>,</span>
<span id="cb124-10"><a href="computation.html#cb124-10" tabindex="-1"></a>    <span class="st">&quot;SMR2006&quot;</span>,</span>
<span id="cb124-11"><a href="computation.html#cb124-11" tabindex="-1"></a>    <span class="st">&quot;SMR2007&quot;</span>,</span>
<span id="cb124-12"><a href="computation.html#cb124-12" tabindex="-1"></a>    <span class="st">&quot;SMR2008&quot;</span>,</span>
<span id="cb124-13"><a href="computation.html#cb124-13" tabindex="-1"></a>    <span class="st">&quot;SMR2009&quot;</span>,</span>
<span id="cb124-14"><a href="computation.html#cb124-14" tabindex="-1"></a>    <span class="st">&quot;SMR2010&quot;</span></span>
<span id="cb124-15"><a href="computation.html#cb124-15" tabindex="-1"></a>  )</span>
<span id="cb124-16"><a href="computation.html#cb124-16" tabindex="-1"></a><span class="co"># Printing first six rows of raw SMRs</span></span>
<span id="cb124-17"><a href="computation.html#cb124-17" tabindex="-1"></a><span class="fu">head</span>(SMR_raw)</span></code></pre></div>
<pre><code>##        SMR2001   SMR2002   SMR2003   SMR2004   SMR2005   SMR2006   SMR2007
## 00AA 0.7550261 0.0000000 1.1000648 0.3636943 0.3560423 0.3429382 1.6547601
## 00AB 1.5638016 1.5768644 1.9498828 1.5135516 2.2413721 1.6253713 1.5558858
## 00AC 0.9031554 0.8366462 0.8656520 0.7223915 0.7955030 0.7699460 0.5665330
## 00AD 1.2084078 1.2384043 1.2289415 1.0349871 1.2063043 1.0253852 0.9848384
## 00AE 0.8975442 1.1530694 0.8972291 0.7471429 0.7584911 0.5869024 0.6335828
## 00AF 0.9147531 0.9750183 1.0130766 0.9217897 0.9381329 0.8516367 0.8655884
##        SMR2008   SMR2009   SMR2010
## 00AA 0.3210586 0.0000000 0.3088328
## 00AB 1.6637225 1.7641760 1.3624329
## 00AC 0.6520466 0.5937205 0.6774503
## 00AD 0.9191171 0.9523676 0.9523676
## 00AE 0.5394928 0.6315370 0.4937471
## 00AF 0.7598103 0.7608397 0.8035037</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="computation.html#cb126-1" tabindex="-1"></a><span class="co"># Summarising raw SMRs</span></span>
<span id="cb126-2"><a href="computation.html#cb126-2" tabindex="-1"></a><span class="fu">summary</span>(SMR_raw)</span></code></pre></div>
<pre><code>##     SMR2001          SMR2002          SMR2003          SMR2004      
##  Min.   :0.3883   Min.   :0.0000   Min.   :0.3616   Min.   :0.2778  
##  1st Qu.:0.7900   1st Qu.:0.8272   1st Qu.:0.8519   1st Qu.:0.7636  
##  Median :0.9496   Median :1.0168   Median :1.0209   Median :0.9266  
##  Mean   :1.0349   Mean   :1.0508   Mean   :1.0895   Mean   :0.9812  
##  3rd Qu.:1.2526   3rd Qu.:1.2364   3rd Qu.:1.3071   3rd Qu.:1.1858  
##  Max.   :1.9861   Max.   :2.2181   Max.   :2.2483   Max.   :1.9811  
##     SMR2005          SMR2006          SMR2007          SMR2008      
##  Min.   :0.3326   Min.   :0.3429   Min.   :0.3509   Min.   :0.3211  
##  1st Qu.:0.7592   1st Qu.:0.7415   1st Qu.:0.7533   1st Qu.:0.7695  
##  Median :0.9573   Median :0.9101   Median :0.9305   Median :0.9404  
##  Mean   :1.0126   Mean   :0.9726   Mean   :0.9743   Mean   :1.0069  
##  3rd Qu.:1.2083   3rd Qu.:1.1586   3rd Qu.:1.1679   3rd Qu.:1.1979  
##  Max.   :2.2414   Max.   :2.0805   Max.   :1.8528   Max.   :2.0567  
##     SMR2009          SMR2010      
##  Min.   :0.0000   Min.   :0.3088  
##  1st Qu.:0.7452   1st Qu.:0.7682  
##  Median :0.8777   Median :0.9337  
##  Mean   :0.9328   Mean   :0.9639  
##  3rd Qu.:1.0934   3rd Qu.:1.1335  
##  Max.   :1.8507   Max.   :2.3856</code></pre>
<p>Attach the values of the raw SMRs to the shapefiles. The function <code>merge()</code> allows us to combine a data frame with a shapefile to plot later.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb128-1"><a href="computation.html#cb128-1" tabindex="-1"></a><span class="co"># Convert row names to ID column</span></span>
<span id="cb128-2"><a href="computation.html#cb128-2" tabindex="-1"></a>SMR_raw <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(SMR_raw, <span class="st">&quot;ID&quot;</span>)</span>
<span id="cb128-3"><a href="computation.html#cb128-3" tabindex="-1"></a><span class="co"># Combine raw SMRs and shapefiles</span></span>
<span id="cb128-4"><a href="computation.html#cb128-4" tabindex="-1"></a>SMRspatial_raw <span class="ot">&lt;-</span> <span class="fu">merge</span>(england, SMR_raw, <span class="at">by =</span> <span class="st">&quot;ID&quot;</span>) </span></code></pre></div>
<p>Use <code>ggplot()</code> and <code>geom_sf()</code> to create a choropleth map such that local authorities are colored by the raw SMR estimate.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb129-1"><a href="computation.html#cb129-1" tabindex="-1"></a><span class="co"># Creating breaks for legend in plot</span></span>
<span id="cb129-2"><a href="computation.html#cb129-2" tabindex="-1"></a>range <span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="fu">min</span>(SMR_raw<span class="sc">$</span>SMR2010) <span class="sc">-</span> <span class="fl">0.01</span>,</span>
<span id="cb129-3"><a href="computation.html#cb129-3" tabindex="-1"></a>      <span class="fu">max</span>(SMR_raw<span class="sc">$</span>SMR2010) <span class="sc">+</span> <span class="fl">0.01</span>,</span>
<span id="cb129-4"><a href="computation.html#cb129-4" tabindex="-1"></a>      <span class="at">length.out =</span> <span class="dv">11</span>)</span>
<span id="cb129-5"><a href="computation.html#cb129-5" tabindex="-1"></a></span>
<span id="cb129-6"><a href="computation.html#cb129-6" tabindex="-1"></a><span class="co"># Creating the map of Raw SMRs in England in 2010</span></span>
<span id="cb129-7"><a href="computation.html#cb129-7" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb129-8"><a href="computation.html#cb129-8" tabindex="-1"></a>  <span class="co"># Choose spatial object and column for plotting</span></span>
<span id="cb129-9"><a href="computation.html#cb129-9" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> SMRspatial_raw, <span class="fu">aes</span>(<span class="at">fill =</span> SMR2010)) <span class="sc">+</span> </span>
<span id="cb129-10"><a href="computation.html#cb129-10" tabindex="-1"></a>  <span class="co"># Break points for colours</span></span>
<span id="cb129-11"><a href="computation.html#cb129-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> range) <span class="sc">+</span> </span>
<span id="cb129-12"><a href="computation.html#cb129-12" tabindex="-1"></a>  <span class="co"># Clear background and plot borders</span></span>
<span id="cb129-13"><a href="computation.html#cb129-13" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb129-14"><a href="computation.html#cb129-14" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb129-15"><a href="computation.html#cb129-15" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb129-16"><a href="computation.html#cb129-16" tabindex="-1"></a>    <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb129-17"><a href="computation.html#cb129-17" tabindex="-1"></a>    <span class="at">rect =</span> <span class="fu">element_blank</span>()</span>
<span id="cb129-18"><a href="computation.html#cb129-18" tabindex="-1"></a>  ) </span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.2%20map-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="mcmc-implementation-of-the-poisson-gamma-model-in-r" class="section level3 unnumbered hasAnchor">
<h3>MCMC implementation of the Poisson-Gamma model in <code>R</code><a href="computation.html#mcmc-implementation-of-the-poisson-gamma-model-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following code shows how to implement the MCMC using <code>R</code> for the COPD example.
We start by defining the constants and the vectors that will be used in the code.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="computation.html#cb130-1" tabindex="-1"></a><span class="co"># observations</span></span>
<span id="cb130-2"><a href="computation.html#cb130-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> observed<span class="sc">$</span>Y2010</span>
<span id="cb130-3"><a href="computation.html#cb130-3" tabindex="-1"></a><span class="co"># offset</span></span>
<span id="cb130-4"><a href="computation.html#cb130-4" tabindex="-1"></a>E <span class="ot">&lt;-</span> expected<span class="sc">$</span>E2010</span>
<span id="cb130-5"><a href="computation.html#cb130-5" tabindex="-1"></a><span class="co"># Number of MCMC iterations</span></span>
<span id="cb130-6"><a href="computation.html#cb130-6" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="dv">20000</span></span>
<span id="cb130-7"><a href="computation.html#cb130-7" tabindex="-1"></a></span>
<span id="cb130-8"><a href="computation.html#cb130-8" tabindex="-1"></a><span class="do">## Initialize objects used in MCMC</span></span>
<span id="cb130-9"><a href="computation.html#cb130-9" tabindex="-1"></a><span class="co"># Matrix for sampled values of parameter theta_i </span></span>
<span id="cb130-10"><a href="computation.html#cb130-10" tabindex="-1"></a>theta <span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="at">ncol =</span> <span class="fu">length</span>(y), <span class="at">nrow =</span> L)</span>
<span id="cb130-11"><a href="computation.html#cb130-11" tabindex="-1"></a><span class="co"># Matrix for fitted values </span></span>
<span id="cb130-12"><a href="computation.html#cb130-12" tabindex="-1"></a>fitted <span class="ot">&lt;-</span>theta</span>
<span id="cb130-13"><a href="computation.html#cb130-13" tabindex="-1"></a><span class="co"># Vector for sampled values of hyper-parameter a</span></span>
<span id="cb130-14"><a href="computation.html#cb130-14" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>() </span>
<span id="cb130-15"><a href="computation.html#cb130-15" tabindex="-1"></a><span class="co"># Vector for sampled values of hyper-parameter b</span></span>
<span id="cb130-16"><a href="computation.html#cb130-16" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>() </span>
<span id="cb130-17"><a href="computation.html#cb130-17" tabindex="-1"></a></span>
<span id="cb130-18"><a href="computation.html#cb130-18" tabindex="-1"></a><span class="do">## Define constants</span></span>
<span id="cb130-19"><a href="computation.html#cb130-19" tabindex="-1"></a><span class="co"># Sample size</span></span>
<span id="cb130-20"><a href="computation.html#cb130-20" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb130-21"><a href="computation.html#cb130-21" tabindex="-1"></a><span class="co"># Parameter of exponential prior for a</span></span>
<span id="cb130-22"><a href="computation.html#cb130-22" tabindex="-1"></a>lambda_a <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb130-23"><a href="computation.html#cb130-23" tabindex="-1"></a><span class="co"># Parameter of exponential prior for b</span></span>
<span id="cb130-24"><a href="computation.html#cb130-24" tabindex="-1"></a>lambda_b <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb130-25"><a href="computation.html#cb130-25" tabindex="-1"></a><span class="co"># standard deviation of the proposal distribution of log a</span></span>
<span id="cb130-26"><a href="computation.html#cb130-26" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fl">0.1</span> </span>
<span id="cb130-27"><a href="computation.html#cb130-27" tabindex="-1"></a><span class="co"># Initialize theta</span></span>
<span id="cb130-28"><a href="computation.html#cb130-28" tabindex="-1"></a>theta[<span class="dv">1</span>, ] <span class="ot">&lt;-</span> y <span class="sc">/</span> E</span>
<span id="cb130-29"><a href="computation.html#cb130-29" tabindex="-1"></a><span class="co"># Initial value sampled from the prior for a</span></span>
<span id="cb130-30"><a href="computation.html#cb130-30" tabindex="-1"></a><span class="co"># REVIEW: In the example of the book theta ~ Ga(a,a) not Ga(a,b)</span></span>
<span id="cb130-31"><a href="computation.html#cb130-31" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">1</span>, lambda_a)</span>
<span id="cb130-32"><a href="computation.html#cb130-32" tabindex="-1"></a><span class="co"># Initial value sampled from the prior for b</span></span>
<span id="cb130-33"><a href="computation.html#cb130-33" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">1</span>, lambda_b) </span>
<span id="cb130-34"><a href="computation.html#cb130-34" tabindex="-1"></a>fitted[<span class="dv">1</span>, ] <span class="ot">&lt;-</span> <span class="fu">rpois</span>(N, E <span class="sc">*</span> theta[<span class="dv">1</span>, ])</span>
<span id="cb130-35"><a href="computation.html#cb130-35" tabindex="-1"></a></span>
<span id="cb130-36"><a href="computation.html#cb130-36" tabindex="-1"></a></span>
<span id="cb130-37"><a href="computation.html#cb130-37" tabindex="-1"></a><span class="co"># Once all the constants and initial values are set we can run the MCMC. </span></span>
<span id="cb130-38"><a href="computation.html#cb130-38" tabindex="-1"></a><span class="co"># The following code shows the MCMC implementation of a Poisson-Gamma model using only `R`.</span></span>
<span id="cb130-39"><a href="computation.html#cb130-39" tabindex="-1"></a><span class="co"># Starting from l=2 as l=1 contains the initial values</span></span>
<span id="cb130-40"><a href="computation.html#cb130-40" tabindex="-1"></a><span class="cf">for</span>(l <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>L) {</span>
<span id="cb130-41"><a href="computation.html#cb130-41" tabindex="-1"></a></span>
<span id="cb130-42"><a href="computation.html#cb130-42" tabindex="-1"></a><span class="co"># Sampling from the posterior full conditional of each theta_i</span></span>
<span id="cb130-43"><a href="computation.html#cb130-43" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb130-44"><a href="computation.html#cb130-44" tabindex="-1"></a>    theta[l, i] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1</span>, (y[i] <span class="sc">+</span> a[(l <span class="sc">-</span> <span class="dv">1</span>)]), <span class="at">rate =</span> (E[i] <span class="sc">+</span> b[(l <span class="sc">-</span> <span class="dv">1</span>)]))</span>
<span id="cb130-45"><a href="computation.html#cb130-45" tabindex="-1"></a>  <span class="co"># Sampling from the posterior full conditional of b</span></span>
<span id="cb130-46"><a href="computation.html#cb130-46" tabindex="-1"></a>  b[l] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1</span>, (N <span class="sc">*</span> a[(l <span class="sc">-</span> <span class="dv">1</span>)] <span class="sc">+</span> <span class="dv">1</span>), <span class="at">rate =</span> (<span class="fu">sum</span>(theta[l, ]) <span class="sc">+</span> lambda_b))</span>
<span id="cb130-47"><a href="computation.html#cb130-47" tabindex="-1"></a>  <span class="co"># Metropolis-Hastings step to sample from the full conditional of &quot;a&quot;</span></span>
<span id="cb130-48"><a href="computation.html#cb130-48" tabindex="-1"></a>  <span class="co"># the new value receives the current value in case the proposed</span></span>
<span id="cb130-49"><a href="computation.html#cb130-49" tabindex="-1"></a>  <span class="co"># value is rejected</span></span>
<span id="cb130-50"><a href="computation.html#cb130-50" tabindex="-1"></a>  a[l] <span class="ot">&lt;-</span> a[l <span class="sc">-</span> <span class="dv">1</span>]</span>
<span id="cb130-51"><a href="computation.html#cb130-51" tabindex="-1"></a>  <span class="co"># Proposal in the log-scale</span></span>
<span id="cb130-52"><a href="computation.html#cb130-52" tabindex="-1"></a>  laprop <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="fu">log</span>(a[l <span class="sc">-</span> <span class="dv">1</span>]), u)</span>
<span id="cb130-53"><a href="computation.html#cb130-53" tabindex="-1"></a>  aprop <span class="ot">&lt;-</span> <span class="fu">exp</span>(laprop)</span>
<span id="cb130-54"><a href="computation.html#cb130-54" tabindex="-1"></a>  <span class="co">#computing the numerator of the M-H step</span></span>
<span id="cb130-55"><a href="computation.html#cb130-55" tabindex="-1"></a>  num <span class="ot">&lt;-</span> N <span class="sc">*</span> (aprop <span class="sc">*</span> (<span class="fu">log</span>(b[l])) <span class="sc">-</span> <span class="fu">lgamma</span>(aprop)) <span class="sc">+</span> (aprop <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(theta[l, ])) <span class="sc">-</span></span>
<span id="cb130-56"><a href="computation.html#cb130-56" tabindex="-1"></a>    aprop <span class="sc">*</span> lambda_a <span class="sc">+</span> <span class="fu">log</span>(aprop)</span>
<span id="cb130-57"><a href="computation.html#cb130-57" tabindex="-1"></a>  <span class="co">#computing the denominator of the M-H step</span></span>
<span id="cb130-58"><a href="computation.html#cb130-58" tabindex="-1"></a>  den <span class="ot">&lt;-</span> N <span class="sc">*</span> (a[l <span class="sc">-</span> <span class="dv">1</span>] <span class="sc">*</span> (<span class="fu">log</span>(b[l])) <span class="sc">-</span> <span class="fu">lgamma</span>(a[l <span class="sc">-</span> <span class="dv">1</span>])) <span class="sc">+</span> (a[(l <span class="sc">-</span> <span class="dv">1</span>)] <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(theta[l, ])) <span class="sc">-</span> </span>
<span id="cb130-59"><a href="computation.html#cb130-59" tabindex="-1"></a>    a[(l <span class="sc">-</span> <span class="dv">1</span>)] <span class="sc">*</span> lambda_a <span class="sc">+</span> <span class="fu">log</span>(a[(l <span class="sc">-</span> <span class="dv">1</span>)])</span>
<span id="cb130-60"><a href="computation.html#cb130-60" tabindex="-1"></a>  <span class="co">#computing the M-H ratio</span></span>
<span id="cb130-61"><a href="computation.html#cb130-61" tabindex="-1"></a>  ratio <span class="ot">&lt;-</span> <span class="fu">exp</span>(num <span class="sc">-</span> den)</span>
<span id="cb130-62"><a href="computation.html#cb130-62" tabindex="-1"></a>  unif <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1</span>)</span>
<span id="cb130-63"><a href="computation.html#cb130-63" tabindex="-1"></a>  <span class="co"># Change the current value if the proposed value is accepted</span></span>
<span id="cb130-64"><a href="computation.html#cb130-64" tabindex="-1"></a>  <span class="cf">if</span> (unif <span class="sc">&lt;</span> ratio)</span>
<span id="cb130-65"><a href="computation.html#cb130-65" tabindex="-1"></a>    a[l] <span class="ot">&lt;-</span> aprop</span>
<span id="cb130-66"><a href="computation.html#cb130-66" tabindex="-1"></a>  fitted[l,] <span class="ot">&lt;-</span> <span class="fu">rpois</span>(N, E <span class="sc">*</span> theta[l,])</span>
<span id="cb130-67"><a href="computation.html#cb130-67" tabindex="-1"></a>}</span></code></pre></div>
<p>After running the MCMC, check convergence of the chains using trace plots, autocorrelation functions and functions from the <code>coda</code> package.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="computation.html#cb131-1" tabindex="-1"></a><span class="co"># Number of burn in samples and thinning</span></span>
<span id="cb131-2"><a href="computation.html#cb131-2" tabindex="-1"></a>burnin <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb131-3"><a href="computation.html#cb131-3" tabindex="-1"></a>thin <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb131-4"><a href="computation.html#cb131-4" tabindex="-1"></a><span class="co"># MCMC samples</span></span>
<span id="cb131-5"><a href="computation.html#cb131-5" tabindex="-1"></a>seqaux <span class="ot">&lt;-</span> <span class="fu">seq</span>(burnin, L, <span class="at">by =</span> thin)</span>
<span id="cb131-6"><a href="computation.html#cb131-6" tabindex="-1"></a></span>
<span id="cb131-7"><a href="computation.html#cb131-7" tabindex="-1"></a><span class="co"># Trace-plots of the parameters</span></span>
<span id="cb131-8"><a href="computation.html#cb131-8" tabindex="-1"></a>xx <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="at">length =</span> <span class="dv">3000</span>)</span>
<span id="cb131-9"><a href="computation.html#cb131-9" tabindex="-1"></a></span>
<span id="cb131-10"><a href="computation.html#cb131-10" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>),<span class="at">pty=</span><span class="st">&quot;m&quot;</span>)</span>
<span id="cb131-11"><a href="computation.html#cb131-11" tabindex="-1"></a><span class="co"># Plot for &quot;a&quot;</span></span>
<span id="cb131-12"><a href="computation.html#cb131-12" tabindex="-1"></a><span class="co">#traceplot for the posterior sample of parameters &#39;a&#39; and &#39;b&#39;</span></span>
<span id="cb131-13"><a href="computation.html#cb131-13" tabindex="-1"></a><span class="fu">plot</span>(a[seqaux], <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Iterations&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;a&quot;</span>)</span>
<span id="cb131-14"><a href="computation.html#cb131-14" tabindex="-1"></a><span class="fu">plot</span>(b[seqaux], <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Iterations&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;b&quot;</span>)</span>
<span id="cb131-15"><a href="computation.html#cb131-15" tabindex="-1"></a><span class="co">#histogram of the posterior distribution of parameter &#39;a&#39;</span></span>
<span id="cb131-16"><a href="computation.html#cb131-16" tabindex="-1"></a><span class="fu">hist</span>(a[seqaux], <span class="at">prob =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="st">&quot;&quot;</span>,)</span>
<span id="cb131-17"><a href="computation.html#cb131-17" tabindex="-1"></a><span class="co">#prior distribution of parameter &quot;a&#39;</span></span>
<span id="cb131-18"><a href="computation.html#cb131-18" tabindex="-1"></a><span class="fu">lines</span>(xx, <span class="fu">dexp</span>(xx, lambda_a), <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb131-19"><a href="computation.html#cb131-19" tabindex="-1"></a><span class="fu">hist</span>(b[seqaux], <span class="at">prob =</span> <span class="dv">1</span>, <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb131-20"><a href="computation.html#cb131-20" tabindex="-1"></a><span class="co">#prior distribution of parameter &quot;a&#39;</span></span>
<span id="cb131-21"><a href="computation.html#cb131-21" tabindex="-1"></a><span class="fu">lines</span>(xx, <span class="fu">dexp</span>(xx, lambda_b), <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb131-22"><a href="computation.html#cb131-22" tabindex="-1"></a><span class="co">#autocorrelation function of the sampled values of parameter &#39;a&#39;</span></span>
<span id="cb131-23"><a href="computation.html#cb131-23" tabindex="-1"></a><span class="fu">acf</span>(a[seqaux],<span class="at">main=</span><span class="st">&quot;ACF for a&quot;</span>)</span>
<span id="cb131-24"><a href="computation.html#cb131-24" tabindex="-1"></a><span class="fu">acf</span>(b[seqaux],<span class="at">main=</span><span class="st">&quot;ACF for b&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.2%20MCMC%20convergence-1.png" width="672" /></p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="computation.html#cb132-1" tabindex="-1"></a><span class="co"># Traceplots of the posterior samples of some of the theta&#39;s</span></span>
<span id="cb132-2"><a href="computation.html#cb132-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>))</span>
<span id="cb132-3"><a href="computation.html#cb132-3" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span>
<span id="cb132-4"><a href="computation.html#cb132-4" tabindex="-1"></a>  <span class="fu">plot</span>(theta[seqaux, i], <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>,<span class="at">xlab=</span><span class="st">&#39;Iteration&#39;</span>,<span class="at">ylab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(theta,i)))</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.2%20MCMC%20convergence-2.png" width="672" /></p>
<p>Other diagnostic tools that can be assessed are the effective sample size (ESS) and <code>Rhat</code>. This can be done using the package <code>coda</code>.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="computation.html#cb133-1" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;ESS a: &quot;</span>, coda<span class="sc">::</span><span class="fu">effectiveSize</span>(a[seqaux]))</span></code></pre></div>
<pre><code>## [1] &quot;ESS a: 32.126114421714&quot;</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="computation.html#cb135-1" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;ESS b: &quot;</span>, coda<span class="sc">::</span><span class="fu">effectiveSize</span>(b[seqaux]))</span></code></pre></div>
<pre><code>## [1] &quot;ESS b: 30.2610882715984&quot;</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="computation.html#cb137-1" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;ESS theta[1]: &quot;</span>, coda<span class="sc">::</span><span class="fu">effectiveSize</span>(theta[seqaux, <span class="dv">1</span>]))</span></code></pre></div>
<pre><code>## [1] &quot;ESS theta[1]: 1001&quot;</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="computation.html#cb139-1" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">&quot;ESS theta[10]: &quot;</span>,coda<span class="sc">::</span><span class="fu">effectiveSize</span>(theta[seqaux, <span class="dv">10</span>]))</span></code></pre></div>
<pre><code>## [1] &quot;ESS theta[10]: 1001&quot;</code></pre>
<p>Clearly, from the trace-plots and the ESS the sampled values for parameters <code>a</code> and <code>b</code> have resulted in poor convergence. The MCMC should be run again and the variance of the proposal of <code>a</code> should be tuned.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="computation.html#cb141-1" tabindex="-1"></a><span class="co"># observations</span></span>
<span id="cb141-2"><a href="computation.html#cb141-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> observed<span class="sc">$</span>Y2010</span>
<span id="cb141-3"><a href="computation.html#cb141-3" tabindex="-1"></a><span class="co"># offset</span></span>
<span id="cb141-4"><a href="computation.html#cb141-4" tabindex="-1"></a>E <span class="ot">&lt;-</span> expected<span class="sc">$</span>E2010</span>
<span id="cb141-5"><a href="computation.html#cb141-5" tabindex="-1"></a><span class="co"># Number of MCMC iterations</span></span>
<span id="cb141-6"><a href="computation.html#cb141-6" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="dv">20000</span></span>
<span id="cb141-7"><a href="computation.html#cb141-7" tabindex="-1"></a>burnin<span class="ot">&lt;-</span><span class="dv">5000</span></span>
<span id="cb141-8"><a href="computation.html#cb141-8" tabindex="-1"></a>check<span class="ot">&lt;-</span><span class="dv">100</span></span>
<span id="cb141-9"><a href="computation.html#cb141-9" tabindex="-1"></a>attempt<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb141-10"><a href="computation.html#cb141-10" tabindex="-1"></a>accept<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb141-11"><a href="computation.html#cb141-11" tabindex="-1"></a></span>
<span id="cb141-12"><a href="computation.html#cb141-12" tabindex="-1"></a><span class="do">## Initialize objects used in MCMC</span></span>
<span id="cb141-13"><a href="computation.html#cb141-13" tabindex="-1"></a><span class="co"># Matrix for sampled values of parameter theta_i </span></span>
<span id="cb141-14"><a href="computation.html#cb141-14" tabindex="-1"></a>theta <span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="at">ncol =</span> <span class="fu">length</span>(y), <span class="at">nrow =</span> L)</span>
<span id="cb141-15"><a href="computation.html#cb141-15" tabindex="-1"></a><span class="co"># Matrix for fitted values </span></span>
<span id="cb141-16"><a href="computation.html#cb141-16" tabindex="-1"></a>fitted <span class="ot">&lt;-</span>theta</span>
<span id="cb141-17"><a href="computation.html#cb141-17" tabindex="-1"></a><span class="co"># Vector for sampled values of hyper-parameter a</span></span>
<span id="cb141-18"><a href="computation.html#cb141-18" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>() </span>
<span id="cb141-19"><a href="computation.html#cb141-19" tabindex="-1"></a><span class="co"># Vector for sampled values of hyper-parameter b</span></span>
<span id="cb141-20"><a href="computation.html#cb141-20" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>() </span>
<span id="cb141-21"><a href="computation.html#cb141-21" tabindex="-1"></a></span>
<span id="cb141-22"><a href="computation.html#cb141-22" tabindex="-1"></a><span class="do">## Define constants</span></span>
<span id="cb141-23"><a href="computation.html#cb141-23" tabindex="-1"></a><span class="co"># Sample size</span></span>
<span id="cb141-24"><a href="computation.html#cb141-24" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb141-25"><a href="computation.html#cb141-25" tabindex="-1"></a><span class="co"># Parameter of exponential prior for a</span></span>
<span id="cb141-26"><a href="computation.html#cb141-26" tabindex="-1"></a>lambda_a <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb141-27"><a href="computation.html#cb141-27" tabindex="-1"></a><span class="co"># Parameter of exponential prior for b</span></span>
<span id="cb141-28"><a href="computation.html#cb141-28" tabindex="-1"></a>lambda_b <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb141-29"><a href="computation.html#cb141-29" tabindex="-1"></a><span class="co"># standard deviation of the proposal distribution of log a</span></span>
<span id="cb141-30"><a href="computation.html#cb141-30" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fl">0.5</span> </span>
<span id="cb141-31"><a href="computation.html#cb141-31" tabindex="-1"></a><span class="co"># Initialize theta</span></span>
<span id="cb141-32"><a href="computation.html#cb141-32" tabindex="-1"></a>theta[<span class="dv">1</span>, ] <span class="ot">&lt;-</span> y <span class="sc">/</span> E</span>
<span id="cb141-33"><a href="computation.html#cb141-33" tabindex="-1"></a><span class="co"># Initial value sampled from the prior for a</span></span>
<span id="cb141-34"><a href="computation.html#cb141-34" tabindex="-1"></a><span class="co"># REVIEW: In the example of the book theta ~ Ga(a,a) not Ga(a,b)</span></span>
<span id="cb141-35"><a href="computation.html#cb141-35" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">1</span>, lambda_a)</span>
<span id="cb141-36"><a href="computation.html#cb141-36" tabindex="-1"></a><span class="co"># Initial value sampled from the prior for b</span></span>
<span id="cb141-37"><a href="computation.html#cb141-37" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">1</span>, lambda_b) </span>
<span id="cb141-38"><a href="computation.html#cb141-38" tabindex="-1"></a>fitted[<span class="dv">1</span>, ] <span class="ot">&lt;-</span> <span class="fu">rpois</span>(N, E <span class="sc">*</span> theta[<span class="dv">1</span>, ])</span>
<span id="cb141-39"><a href="computation.html#cb141-39" tabindex="-1"></a></span>
<span id="cb141-40"><a href="computation.html#cb141-40" tabindex="-1"></a><span class="co"># Once all the constants and initial values are set we can run the MCMC. </span></span>
<span id="cb141-41"><a href="computation.html#cb141-41" tabindex="-1"></a><span class="co"># The following code shows the MCMC implementation of a Poisson-Gamma model using only `R`.</span></span>
<span id="cb141-42"><a href="computation.html#cb141-42" tabindex="-1"></a><span class="co"># Starting from l=2 as l=1 contains the initial values</span></span>
<span id="cb141-43"><a href="computation.html#cb141-43" tabindex="-1"></a><span class="cf">for</span>(l <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>L) {</span>
<span id="cb141-44"><a href="computation.html#cb141-44" tabindex="-1"></a></span>
<span id="cb141-45"><a href="computation.html#cb141-45" tabindex="-1"></a><span class="co"># Sampling from the posterior full conditional of each theta_i</span></span>
<span id="cb141-46"><a href="computation.html#cb141-46" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb141-47"><a href="computation.html#cb141-47" tabindex="-1"></a>    theta[l, i] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1</span>, <span class="at">shape=</span>(y[i] <span class="sc">+</span> a[(l <span class="sc">-</span> <span class="dv">1</span>)]), <span class="at">rate =</span>(E[i] <span class="sc">+</span> b[(l <span class="sc">-</span> <span class="dv">1</span>)]))</span>
<span id="cb141-48"><a href="computation.html#cb141-48" tabindex="-1"></a>  <span class="co"># Sampling from the posterior full conditional of b</span></span>
<span id="cb141-49"><a href="computation.html#cb141-49" tabindex="-1"></a>  b[l] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1</span>, <span class="at">shape=</span>(N <span class="sc">*</span> a[(l <span class="sc">-</span> <span class="dv">1</span>)] <span class="sc">+</span> <span class="dv">1</span>), <span class="at">rate=</span>(<span class="fu">sum</span>(theta[l, ]) <span class="sc">+</span> lambda_b))</span>
<span id="cb141-50"><a href="computation.html#cb141-50" tabindex="-1"></a>  <span class="co"># Metropolis-Hastings step to sample from the full conditional of &quot;a&quot;</span></span>
<span id="cb141-51"><a href="computation.html#cb141-51" tabindex="-1"></a>  <span class="co"># the new value receives the current value in case the proposed</span></span>
<span id="cb141-52"><a href="computation.html#cb141-52" tabindex="-1"></a>  <span class="co"># value is rejected</span></span>
<span id="cb141-53"><a href="computation.html#cb141-53" tabindex="-1"></a>  a[l] <span class="ot">&lt;-</span> a[l <span class="sc">-</span> <span class="dv">1</span>]</span>
<span id="cb141-54"><a href="computation.html#cb141-54" tabindex="-1"></a>  <span class="co"># Proposal in the log-scale</span></span>
<span id="cb141-55"><a href="computation.html#cb141-55" tabindex="-1"></a>  laprop <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="fu">log</span>(a[l <span class="sc">-</span> <span class="dv">1</span>]), u)</span>
<span id="cb141-56"><a href="computation.html#cb141-56" tabindex="-1"></a>  aprop <span class="ot">&lt;-</span> <span class="fu">exp</span>(laprop)</span>
<span id="cb141-57"><a href="computation.html#cb141-57" tabindex="-1"></a>  <span class="co">#computing the numerator of the M-H step</span></span>
<span id="cb141-58"><a href="computation.html#cb141-58" tabindex="-1"></a>  num <span class="ot">&lt;-</span> N <span class="sc">*</span> ((aprop) <span class="sc">*</span> (<span class="fu">log</span>(b[l])) <span class="sc">-</span> <span class="fu">lgamma</span>(aprop)) <span class="sc">+</span> (aprop <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(theta[l, ])) <span class="sc">-</span></span>
<span id="cb141-59"><a href="computation.html#cb141-59" tabindex="-1"></a>    aprop <span class="sc">*</span> lambda_a <span class="sc">+</span> <span class="fu">log</span>(aprop)</span>
<span id="cb141-60"><a href="computation.html#cb141-60" tabindex="-1"></a>  <span class="co">#computing the denominator of the M-H step</span></span>
<span id="cb141-61"><a href="computation.html#cb141-61" tabindex="-1"></a>  den <span class="ot">&lt;-</span> N <span class="sc">*</span> ((a[l <span class="sc">-</span> <span class="dv">1</span>]) <span class="sc">*</span> (<span class="fu">log</span>(b[l])) <span class="sc">-</span> <span class="fu">lgamma</span>(a[l <span class="sc">-</span> <span class="dv">1</span>])) <span class="sc">+</span></span>
<span id="cb141-62"><a href="computation.html#cb141-62" tabindex="-1"></a>    (a[(l <span class="sc">-</span> <span class="dv">1</span>)] <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(theta[l, ])) <span class="sc">-</span> a[(l <span class="sc">-</span> <span class="dv">1</span>)] <span class="sc">*</span> lambda_a <span class="sc">+</span> <span class="fu">log</span>(a[(l <span class="sc">-</span> <span class="dv">1</span>)])</span>
<span id="cb141-63"><a href="computation.html#cb141-63" tabindex="-1"></a>  <span class="co">#computing the M-H ratio</span></span>
<span id="cb141-64"><a href="computation.html#cb141-64" tabindex="-1"></a>  attempt<span class="ot">&lt;-</span>attempt<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb141-65"><a href="computation.html#cb141-65" tabindex="-1"></a>  ratio <span class="ot">&lt;-</span> <span class="fu">exp</span>(num <span class="sc">-</span> den)</span>
<span id="cb141-66"><a href="computation.html#cb141-66" tabindex="-1"></a>  unif <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1</span>)</span>
<span id="cb141-67"><a href="computation.html#cb141-67" tabindex="-1"></a>  <span class="co"># Change the current value if the proposed value is accepted</span></span>
<span id="cb141-68"><a href="computation.html#cb141-68" tabindex="-1"></a>  <span class="cf">if</span> (unif <span class="sc">&lt;</span> ratio){</span>
<span id="cb141-69"><a href="computation.html#cb141-69" tabindex="-1"></a>    accept<span class="ot">&lt;-</span>accept<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb141-70"><a href="computation.html#cb141-70" tabindex="-1"></a>    a[l] <span class="ot">&lt;-</span> aprop</span>
<span id="cb141-71"><a href="computation.html#cb141-71" tabindex="-1"></a>  }</span>
<span id="cb141-72"><a href="computation.html#cb141-72" tabindex="-1"></a>  <span class="co"># TUNING!</span></span>
<span id="cb141-73"><a href="computation.html#cb141-73" tabindex="-1"></a>  <span class="cf">if</span>(l<span class="sc">&lt;</span>burnin <span class="sc">&amp;</span> attempt<span class="sc">==</span>check){</span>
<span id="cb141-74"><a href="computation.html#cb141-74" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">&quot;Can sd of &quot;</span>, <span class="fu">round</span>(u,<span class="dv">3</span>),</span>
<span id="cb141-75"><a href="computation.html#cb141-75" tabindex="-1"></a>                   <span class="st">&quot; for a gave acc rate &quot;</span>,accept<span class="sc">/</span>attempt)) </span>
<span id="cb141-76"><a href="computation.html#cb141-76" tabindex="-1"></a>      <span class="cf">if</span>(accept<span class="sc">/</span>attempt<span class="sc">&lt;</span><span class="fl">0.2</span>){u<span class="ot">&lt;-</span>u<span class="sc">*</span><span class="fl">0.8</span>}</span>
<span id="cb141-77"><a href="computation.html#cb141-77" tabindex="-1"></a>      <span class="cf">if</span>(accept<span class="sc">/</span>attempt<span class="sc">&gt;</span><span class="fl">0.6</span>){u<span class="ot">&lt;-</span>u<span class="sc">*</span><span class="fl">1.2</span>}</span>
<span id="cb141-78"><a href="computation.html#cb141-78" tabindex="-1"></a>      accept <span class="ot">&lt;-</span> attempt <span class="ot">&lt;-</span> <span class="dv">0</span>  </span>
<span id="cb141-79"><a href="computation.html#cb141-79" tabindex="-1"></a>    }</span>
<span id="cb141-80"><a href="computation.html#cb141-80" tabindex="-1"></a>  fitted[l,] <span class="ot">&lt;-</span> <span class="fu">rpois</span>(N, E <span class="sc">*</span> theta[l,])</span>
<span id="cb141-81"><a href="computation.html#cb141-81" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;Can sd of 0.5 for a gave acc rate 0.19&quot;
## [1] &quot;Can sd of 0.4 for a gave acc rate 0.12&quot;
## [1] &quot;Can sd of 0.32 for a gave acc rate 0.08&quot;
## [1] &quot;Can sd of 0.256 for a gave acc rate 0.05&quot;
## [1] &quot;Can sd of 0.205 for a gave acc rate 0.15&quot;
## [1] &quot;Can sd of 0.164 for a gave acc rate 0.14&quot;
## [1] &quot;Can sd of 0.131 for a gave acc rate 0.15&quot;
## [1] &quot;Can sd of 0.105 for a gave acc rate 0.19&quot;
## [1] &quot;Can sd of 0.084 for a gave acc rate 0.16&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.29&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.26&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.26&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.31&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.3&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.24&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.29&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.24&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.28&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.29&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.28&quot;
## [1] &quot;Can sd of 0.067 for a gave acc rate 0.19&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.36&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.37&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.42&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.33&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.26&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.27&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.3&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.42&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.36&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.3&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.26&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.31&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.28&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.34&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.34&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.3&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.34&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.3&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.37&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.34&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.36&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.32&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.32&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.41&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.45&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.32&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.35&quot;
## [1] &quot;Can sd of 0.054 for a gave acc rate 0.36&quot;</code></pre>
<p>Now that we have guaranteed the convergence of the chains, we can look at the posterior summaries.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="computation.html#cb143-1" tabindex="-1"></a><span class="co"># Posterior summaries of theta_i</span></span>
<span id="cb143-2"><a href="computation.html#cb143-2" tabindex="-1"></a>meantheta <span class="ot">&lt;-</span> <span class="fu">apply</span>(theta, <span class="dv">2</span>, mean)</span>
<span id="cb143-3"><a href="computation.html#cb143-3" tabindex="-1"></a>q025theta <span class="ot">&lt;-</span> <span class="fu">apply</span>(theta, <span class="dv">2</span>, <span class="cf">function</span>(x)</span>
<span id="cb143-4"><a href="computation.html#cb143-4" tabindex="-1"></a>  <span class="fu">quantile</span>(x, <span class="fl">0.025</span>))</span>
<span id="cb143-5"><a href="computation.html#cb143-5" tabindex="-1"></a>q975theta <span class="ot">&lt;-</span> <span class="fu">apply</span>(theta, <span class="dv">2</span>, <span class="cf">function</span>(x)</span>
<span id="cb143-6"><a href="computation.html#cb143-6" tabindex="-1"></a>  <span class="fu">quantile</span>(x, <span class="fl">0.975</span>))</span>
<span id="cb143-7"><a href="computation.html#cb143-7" tabindex="-1"></a></span>
<span id="cb143-8"><a href="computation.html#cb143-8" tabindex="-1"></a><span class="co"># Plot the mean and 95% CIs for the thetas</span></span>
<span id="cb143-9"><a href="computation.html#cb143-9" tabindex="-1"></a></span>
<span id="cb143-10"><a href="computation.html#cb143-10" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb143-11"><a href="computation.html#cb143-11" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb143-12"><a href="computation.html#cb143-12" tabindex="-1"></a>  meantheta,</span>
<span id="cb143-13"><a href="computation.html#cb143-13" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb143-14"><a href="computation.html#cb143-14" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.8</span>,</span>
<span id="cb143-15"><a href="computation.html#cb143-15" tabindex="-1"></a>  <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>,</span>
<span id="cb143-16"><a href="computation.html#cb143-16" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;Borough&quot;</span>,</span>
<span id="cb143-17"><a href="computation.html#cb143-17" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">&quot;Posterior Summary Rate&quot;</span>,</span>
<span id="cb143-18"><a href="computation.html#cb143-18" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(q025theta), <span class="fu">max</span>(q975theta))</span>
<span id="cb143-19"><a href="computation.html#cb143-19" tabindex="-1"></a>)</span>
<span id="cb143-20"><a href="computation.html#cb143-20" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb143-21"><a href="computation.html#cb143-21" tabindex="-1"></a>  <span class="fu">segments</span>(i, q025theta[i], i, q975theta[i])</span>
<span id="cb143-22"><a href="computation.html#cb143-22" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.2%20MCMC%20posterior%20summary-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="computation.html#cb144-1" tabindex="-1"></a><span class="co"># Posterior summary of fitted values</span></span>
<span id="cb144-2"><a href="computation.html#cb144-2" tabindex="-1"></a></span>
<span id="cb144-3"><a href="computation.html#cb144-3" tabindex="-1"></a>meanfit <span class="ot">&lt;-</span> <span class="fu">apply</span>(fitted, <span class="dv">2</span>, mean)</span>
<span id="cb144-4"><a href="computation.html#cb144-4" tabindex="-1"></a>q025fit <span class="ot">&lt;-</span> <span class="fu">apply</span>(fitted, <span class="dv">2</span>, <span class="cf">function</span>(x)</span>
<span id="cb144-5"><a href="computation.html#cb144-5" tabindex="-1"></a>  <span class="fu">quantile</span>(x, <span class="fl">0.025</span>))</span>
<span id="cb144-6"><a href="computation.html#cb144-6" tabindex="-1"></a>q975fit <span class="ot">&lt;-</span> <span class="fu">apply</span>(fitted, <span class="dv">2</span>, <span class="cf">function</span>(x)</span>
<span id="cb144-7"><a href="computation.html#cb144-7" tabindex="-1"></a>  <span class="fu">quantile</span>(x, <span class="fl">0.975</span>))</span>
<span id="cb144-8"><a href="computation.html#cb144-8" tabindex="-1"></a></span>
<span id="cb144-9"><a href="computation.html#cb144-9" tabindex="-1"></a><span class="co"># Plot mean and 95% CIs for the fitted values</span></span>
<span id="cb144-10"><a href="computation.html#cb144-10" tabindex="-1"></a></span>
<span id="cb144-11"><a href="computation.html#cb144-11" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb144-12"><a href="computation.html#cb144-12" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb144-13"><a href="computation.html#cb144-13" tabindex="-1"></a>  y,</span>
<span id="cb144-14"><a href="computation.html#cb144-14" tabindex="-1"></a>  meanfit,</span>
<span id="cb144-15"><a href="computation.html#cb144-15" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(q025fit), <span class="fu">max</span>(q975fit)),</span>
<span id="cb144-16"><a href="computation.html#cb144-16" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;Observed&quot;</span>,</span>
<span id="cb144-17"><a href="computation.html#cb144-17" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">&quot;Fitted&quot;</span>,</span>
<span id="cb144-18"><a href="computation.html#cb144-18" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb144-19"><a href="computation.html#cb144-19" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.7</span>,</span>
<span id="cb144-20"><a href="computation.html#cb144-20" tabindex="-1"></a>  <span class="at">bty =</span> <span class="st">&quot;n&quot;</span></span>
<span id="cb144-21"><a href="computation.html#cb144-21" tabindex="-1"></a>)</span>
<span id="cb144-22"><a href="computation.html#cb144-22" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb144-23"><a href="computation.html#cb144-23" tabindex="-1"></a>  <span class="fu">segments</span>(y[i], q025fit[i], y[i], q975fit[i])</span>
<span id="cb144-24"><a href="computation.html#cb144-24" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="dv">0</span>, <span class="at">b =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.2%20MCMC%20posterior%20summary-2.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="code-for-the-poisson-gamma-model-in-nimble" class="section level2 unnumbered hasAnchor">
<h2>Code for the Poisson-Gamma model in Nimble<a href="computation.html#code-for-the-poisson-gamma-model-in-nimble" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="computation.html#cb145-1" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;nimble&quot;</span>)</span>
<span id="cb145-2"><a href="computation.html#cb145-2" tabindex="-1"></a><span class="co"># Define the model </span></span>
<span id="cb145-3"><a href="computation.html#cb145-3" tabindex="-1"></a>Example6_2Code <span class="ot">&lt;-</span> <span class="fu">nimbleCode</span>({</span>
<span id="cb145-4"><a href="computation.html#cb145-4" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N) {</span>
<span id="cb145-5"><a href="computation.html#cb145-5" tabindex="-1"></a>    Y[i] <span class="sc">~</span> <span class="fu">dpois</span>(mu[i])</span>
<span id="cb145-6"><a href="computation.html#cb145-6" tabindex="-1"></a>    <span class="fu">log</span>(mu[i]) <span class="ot">&lt;-</span> <span class="fu">log</span>(E[i]) <span class="sc">+</span> theta[i]</span>
<span id="cb145-7"><a href="computation.html#cb145-7" tabindex="-1"></a>    theta[i] <span class="sc">~</span> <span class="fu">dgamma</span>(a,b)</span>
<span id="cb145-8"><a href="computation.html#cb145-8" tabindex="-1"></a>  }</span>
<span id="cb145-9"><a href="computation.html#cb145-9" tabindex="-1"></a>  </span>
<span id="cb145-10"><a href="computation.html#cb145-10" tabindex="-1"></a>  <span class="co"># Priors</span></span>
<span id="cb145-11"><a href="computation.html#cb145-11" tabindex="-1"></a>  a <span class="sc">~</span> <span class="fu">dexp</span>(<span class="dv">1</span>)</span>
<span id="cb145-12"><a href="computation.html#cb145-12" tabindex="-1"></a>  b <span class="sc">~</span> <span class="fu">dexp</span>(<span class="dv">1</span>)</span>
<span id="cb145-13"><a href="computation.html#cb145-13" tabindex="-1"></a>  </span>
<span id="cb145-14"><a href="computation.html#cb145-14" tabindex="-1"></a>})</span>
<span id="cb145-15"><a href="computation.html#cb145-15" tabindex="-1"></a></span>
<span id="cb145-16"><a href="computation.html#cb145-16" tabindex="-1"></a><span class="co"># Read the data and define the constants, data and initials lists for the `Nimble` model.</span></span>
<span id="cb145-17"><a href="computation.html#cb145-17" tabindex="-1"></a></span>
<span id="cb145-18"><a href="computation.html#cb145-18" tabindex="-1"></a>ex.const <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb145-19"><a href="computation.html#cb145-19" tabindex="-1"></a>  <span class="at">E =</span> expected<span class="sc">$</span>E2010,</span>
<span id="cb145-20"><a href="computation.html#cb145-20" tabindex="-1"></a>  <span class="at">N=</span><span class="fu">length</span>(observed<span class="sc">$</span>Y2010))</span>
<span id="cb145-21"><a href="computation.html#cb145-21" tabindex="-1"></a></span>
<span id="cb145-22"><a href="computation.html#cb145-22" tabindex="-1"></a>ex.data <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">Y =</span> observed<span class="sc">$</span>Y2010)</span>
<span id="cb145-23"><a href="computation.html#cb145-23" tabindex="-1"></a></span>
<span id="cb145-24"><a href="computation.html#cb145-24" tabindex="-1"></a>inits <span class="ot">&lt;-</span> <span class="cf">function</span>()</span>
<span id="cb145-25"><a href="computation.html#cb145-25" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">theta =</span> <span class="fu">rgamma</span>(<span class="fu">length</span>(y),<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">a=</span><span class="fu">rexp</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">b=</span><span class="fu">rexp</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb145-26"><a href="computation.html#cb145-26" tabindex="-1"></a></span>
<span id="cb145-27"><a href="computation.html#cb145-27" tabindex="-1"></a><span class="co"># Define parameters to monitor and run the model</span></span>
<span id="cb145-28"><a href="computation.html#cb145-28" tabindex="-1"></a></span>
<span id="cb145-29"><a href="computation.html#cb145-29" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;theta&quot;</span>)</span>
<span id="cb145-30"><a href="computation.html#cb145-30" tabindex="-1"></a></span>
<span id="cb145-31"><a href="computation.html#cb145-31" tabindex="-1"></a>mcmc.out <span class="ot">&lt;-</span> <span class="fu">nimbleMCMC</span>(</span>
<span id="cb145-32"><a href="computation.html#cb145-32" tabindex="-1"></a>  <span class="at">code =</span> Example6_2Code,</span>
<span id="cb145-33"><a href="computation.html#cb145-33" tabindex="-1"></a>  <span class="at">data =</span> ex.data,</span>
<span id="cb145-34"><a href="computation.html#cb145-34" tabindex="-1"></a>  <span class="at">constants =</span> ex.const,</span>
<span id="cb145-35"><a href="computation.html#cb145-35" tabindex="-1"></a>  <span class="at">inits =</span> inits,</span>
<span id="cb145-36"><a href="computation.html#cb145-36" tabindex="-1"></a>  <span class="at">monitors =</span> params,</span>
<span id="cb145-37"><a href="computation.html#cb145-37" tabindex="-1"></a>  <span class="at">niter =</span> <span class="dv">22000</span>,</span>
<span id="cb145-38"><a href="computation.html#cb145-38" tabindex="-1"></a>  <span class="at">nburnin =</span> <span class="dv">2000</span>,</span>
<span id="cb145-39"><a href="computation.html#cb145-39" tabindex="-1"></a>  <span class="at">thin =</span> <span class="dv">10</span>,</span>
<span id="cb145-40"><a href="computation.html#cb145-40" tabindex="-1"></a>  <span class="at">WAIC =</span> <span class="cn">TRUE</span>,</span>
<span id="cb145-41"><a href="computation.html#cb145-41" tabindex="-1"></a>  <span class="at">nchains =</span> <span class="dv">2</span>,</span>
<span id="cb145-42"><a href="computation.html#cb145-42" tabindex="-1"></a>  <span class="at">samplesAsCodaMCMC =</span> <span class="cn">TRUE</span></span>
<span id="cb145-43"><a href="computation.html#cb145-43" tabindex="-1"></a>)</span></code></pre></div>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="computation.html#cb146-1" tabindex="-1"></a>mvSamples <span class="ot">&lt;-</span> mcmc.out<span class="sc">$</span>samples</span>
<span id="cb146-2"><a href="computation.html#cb146-2" tabindex="-1"></a></span>
<span id="cb146-3"><a href="computation.html#cb146-3" tabindex="-1"></a><span class="co">#trace plots of beta1</span></span>
<span id="cb146-4"><a href="computation.html#cb146-4" tabindex="-1"></a><span class="fu">plot</span>(mvSamples[, <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.2%20output%20nimble-1.png" width="672" /></p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="computation.html#cb147-1" tabindex="-1"></a><span class="fu">plot</span>(mvSamples[, <span class="fu">c</span>(<span class="st">&quot;b&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.2%20output%20nimble-2.png" width="672" /></p>
</div>
<div id="example-6.3-fitting-a-poisson-regression-model" class="section level2 unnumbered hasAnchor">
<h2>Example 6.3: Fitting a Poisson regression model<a href="computation.html#example-6.3-fitting-a-poisson-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this example, we consider the Poisson log-linear model seen in Chapter 2, Section 2.7. We consider the observed and expected number of cases of respiratory mortality in small areas in the UK from a study examining the long-term effects of air pollution (Elliott, Shaddick, Wakefield, de Hoogh, &amp; Briggs, 2007).</p>
<p><span class="math display">\[\begin{eqnarray}
\label{eqn:cum1c2}  \log \mu_{l} =  \beta_0 +  \beta_1
X_{l} + \beta_{d}X_{l}
\end{eqnarray}\]</span>
where <span class="math inline">\(\beta_1\)</span> represents the effect of exposure and <span class="math inline">\(\beta_d\)</span> is the
effect of the area-level covariate.</p>
<div id="nimble" class="section level3 unnumbered hasAnchor">
<h3>Nimble<a href="computation.html#nimble" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Load <code>nimble package</code></p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb148-1"><a href="computation.html#cb148-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;nimble&quot;</span>)</span></code></pre></div>
<p>The NIMBLE code to fit this model is as follows:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="computation.html#cb149-1" tabindex="-1"></a><span class="co"># Define the model </span></span>
<span id="cb149-2"><a href="computation.html#cb149-2" tabindex="-1"></a>Example6_3Code <span class="ot">&lt;-</span> <span class="fu">nimbleCode</span>({</span>
<span id="cb149-3"><a href="computation.html#cb149-3" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N) {</span>
<span id="cb149-4"><a href="computation.html#cb149-4" tabindex="-1"></a>    Y[i] <span class="sc">~</span> <span class="fu">dpois</span>(mu[i])</span>
<span id="cb149-5"><a href="computation.html#cb149-5" tabindex="-1"></a>    <span class="fu">log</span>(mu[i]) <span class="ot">&lt;-</span> <span class="fu">log</span>(E[i]) <span class="sc">+</span> beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> X1[i] <span class="sc">+</span> beta2 <span class="sc">*</span> X2[i]</span>
<span id="cb149-6"><a href="computation.html#cb149-6" tabindex="-1"></a>  }</span>
<span id="cb149-7"><a href="computation.html#cb149-7" tabindex="-1"></a>  </span>
<span id="cb149-8"><a href="computation.html#cb149-8" tabindex="-1"></a>  <span class="co"># Priors</span></span>
<span id="cb149-9"><a href="computation.html#cb149-9" tabindex="-1"></a>  beta0 <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="dv">0</span> , <span class="at">sd =</span> <span class="dv">100</span>)</span>
<span id="cb149-10"><a href="computation.html#cb149-10" tabindex="-1"></a>  beta1 <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="dv">0</span> , <span class="at">sd =</span> <span class="dv">100</span>)</span>
<span id="cb149-11"><a href="computation.html#cb149-11" tabindex="-1"></a>  beta2 <span class="sc">~</span> <span class="fu">dnorm</span> (<span class="dv">0</span> , <span class="at">sd =</span> <span class="dv">100</span>)</span>
<span id="cb149-12"><a href="computation.html#cb149-12" tabindex="-1"></a>  </span>
<span id="cb149-13"><a href="computation.html#cb149-13" tabindex="-1"></a>  <span class="co"># Functions of interest:</span></span>
<span id="cb149-14"><a href="computation.html#cb149-14" tabindex="-1"></a>  base <span class="ot">&lt;-</span> <span class="fu">exp</span>(beta0)</span>
<span id="cb149-15"><a href="computation.html#cb149-15" tabindex="-1"></a>  RR <span class="ot">&lt;-</span> <span class="fu">exp</span>(beta1)</span>
<span id="cb149-16"><a href="computation.html#cb149-16" tabindex="-1"></a>})</span>
<span id="cb149-17"><a href="computation.html#cb149-17" tabindex="-1"></a></span>
<span id="cb149-18"><a href="computation.html#cb149-18" tabindex="-1"></a><span class="co"># Read the data and define the constants, data and initials lists for the `Nimble` model.</span></span>
<span id="cb149-19"><a href="computation.html#cb149-19" tabindex="-1"></a></span>
<span id="cb149-20"><a href="computation.html#cb149-20" tabindex="-1"></a><span class="co"># REVIEW: Is this another version of the COPD data? Is there a data dictionary for this dataset?</span></span>
<span id="cb149-21"><a href="computation.html#cb149-21" tabindex="-1"></a></span>
<span id="cb149-22"><a href="computation.html#cb149-22" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/DataExample53.csv&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb149-23"><a href="computation.html#cb149-23" tabindex="-1"></a></span>
<span id="cb149-24"><a href="computation.html#cb149-24" tabindex="-1"></a>ex.const <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb149-25"><a href="computation.html#cb149-25" tabindex="-1"></a>  <span class="at">N =</span> <span class="fu">nrow</span>(data),</span>
<span id="cb149-26"><a href="computation.html#cb149-26" tabindex="-1"></a>  <span class="at">E =</span> data<span class="sc">$</span>exp_lungc65pls,</span>
<span id="cb149-27"><a href="computation.html#cb149-27" tabindex="-1"></a>  <span class="at">X1 =</span> <span class="fu">as.vector</span>(<span class="fu">scale</span>(data<span class="sc">$</span>k3)),</span>
<span id="cb149-28"><a href="computation.html#cb149-28" tabindex="-1"></a>  <span class="at">X2 =</span> <span class="fu">as.vector</span>(<span class="fu">scale</span>(data<span class="sc">$</span>k2))</span>
<span id="cb149-29"><a href="computation.html#cb149-29" tabindex="-1"></a>)</span>
<span id="cb149-30"><a href="computation.html#cb149-30" tabindex="-1"></a></span>
<span id="cb149-31"><a href="computation.html#cb149-31" tabindex="-1"></a>ex.data <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">Y =</span> data<span class="sc">$</span>lungc65pls)</span>
<span id="cb149-32"><a href="computation.html#cb149-32" tabindex="-1"></a></span>
<span id="cb149-33"><a href="computation.html#cb149-33" tabindex="-1"></a>inits <span class="ot">&lt;-</span> <span class="cf">function</span>()</span>
<span id="cb149-34"><a href="computation.html#cb149-34" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">beta0 =</span> <span class="fu">rnorm</span>(<span class="dv">1</span>),</span>
<span id="cb149-35"><a href="computation.html#cb149-35" tabindex="-1"></a>       <span class="at">beta1 =</span> <span class="fu">rnorm</span>(<span class="dv">1</span>),</span>
<span id="cb149-36"><a href="computation.html#cb149-36" tabindex="-1"></a>       <span class="at">beta2 =</span> <span class="fu">rnorm</span>(<span class="dv">1</span>))</span>
<span id="cb149-37"><a href="computation.html#cb149-37" tabindex="-1"></a></span>
<span id="cb149-38"><a href="computation.html#cb149-38" tabindex="-1"></a><span class="co"># Define parameters to monitor and run the model</span></span>
<span id="cb149-39"><a href="computation.html#cb149-39" tabindex="-1"></a></span>
<span id="cb149-40"><a href="computation.html#cb149-40" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;beta0&quot;</span>, <span class="st">&quot;beta1&quot;</span>, <span class="st">&quot;beta2&quot;</span>, <span class="st">&quot;base&quot;</span>, <span class="st">&quot;RR&quot;</span>)</span>
<span id="cb149-41"><a href="computation.html#cb149-41" tabindex="-1"></a></span>
<span id="cb149-42"><a href="computation.html#cb149-42" tabindex="-1"></a>mcmc.out <span class="ot">&lt;-</span> <span class="fu">nimbleMCMC</span>(</span>
<span id="cb149-43"><a href="computation.html#cb149-43" tabindex="-1"></a>  <span class="at">code =</span> Example6_3Code,</span>
<span id="cb149-44"><a href="computation.html#cb149-44" tabindex="-1"></a>  <span class="at">data =</span> ex.data,</span>
<span id="cb149-45"><a href="computation.html#cb149-45" tabindex="-1"></a>  <span class="at">constants =</span> ex.const,</span>
<span id="cb149-46"><a href="computation.html#cb149-46" tabindex="-1"></a>  <span class="at">inits =</span> inits,</span>
<span id="cb149-47"><a href="computation.html#cb149-47" tabindex="-1"></a>  <span class="at">monitors =</span> params,</span>
<span id="cb149-48"><a href="computation.html#cb149-48" tabindex="-1"></a>  <span class="at">niter =</span> <span class="dv">22000</span>,</span>
<span id="cb149-49"><a href="computation.html#cb149-49" tabindex="-1"></a>  <span class="at">nburnin =</span> <span class="dv">2000</span>,</span>
<span id="cb149-50"><a href="computation.html#cb149-50" tabindex="-1"></a>  <span class="at">thin =</span> <span class="dv">10</span>,</span>
<span id="cb149-51"><a href="computation.html#cb149-51" tabindex="-1"></a>  <span class="at">WAIC =</span> <span class="cn">TRUE</span>,</span>
<span id="cb149-52"><a href="computation.html#cb149-52" tabindex="-1"></a>  <span class="at">nchains =</span> <span class="dv">3</span>,</span>
<span id="cb149-53"><a href="computation.html#cb149-53" tabindex="-1"></a>  <span class="at">samplesAsCodaMCMC =</span> <span class="cn">TRUE</span></span>
<span id="cb149-54"><a href="computation.html#cb149-54" tabindex="-1"></a>)</span></code></pre></div>
<!-- Check the WAIC.  -->
<!-- ```{r Ex 6.3 nimble WAIC} -->
<!-- mcmc.out$WAIC -->
<!-- ``` -->
<p>Checking the trace plots and posterior summaries for each of the parameters.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="computation.html#cb150-1" tabindex="-1"></a>mvSamples <span class="ot">&lt;-</span> mcmc.out<span class="sc">$</span>samples</span>
<span id="cb150-2"><a href="computation.html#cb150-2" tabindex="-1"></a><span class="co">#trace plots of beta1</span></span>
<span id="cb150-3"><a href="computation.html#cb150-3" tabindex="-1"></a><span class="fu">plot</span>(mvSamples[, <span class="fu">c</span>(<span class="st">&quot;beta1&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.3%20nimble%20traceplots-1.png" width="672" /></p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="computation.html#cb151-1" tabindex="-1"></a><span class="co">#trace plots of base</span></span>
<span id="cb151-2"><a href="computation.html#cb151-2" tabindex="-1"></a><span class="fu">plot</span>(mvSamples[, <span class="fu">c</span>(<span class="st">&quot;base&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.3%20nimble%20traceplots-2.png" width="672" /></p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="computation.html#cb152-1" tabindex="-1"></a><span class="co">#trace plots of RR</span></span>
<span id="cb152-2"><a href="computation.html#cb152-2" tabindex="-1"></a><span class="fu">plot</span>(mvSamples[, <span class="fu">c</span>(<span class="st">&quot;RR&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.3%20nimble%20traceplots-3.png" width="672" /></p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="computation.html#cb153-1" tabindex="-1"></a><span class="co">#posterior summary of base and RR</span></span>
<span id="cb153-2"><a href="computation.html#cb153-2" tabindex="-1"></a><span class="fu">summary</span>(mvSamples[, <span class="fu">c</span>(<span class="st">&quot;base&quot;</span>,<span class="st">&quot;RR&quot;</span>)])</span></code></pre></div>
<pre><code>## 
## Iterations = 1:2000
## Thinning interval = 1 
## Number of chains = 3 
## Sample size per chain = 2000 
## 
## 1. Empirical mean and standard deviation for each variable,
##    plus standard error of the mean:
## 
##       Mean      SD  Naive SE Time-series SE
## base 1.129 0.01260 0.0001627      0.0001666
## RR   1.015 0.01744 0.0002251      0.0003443
## 
## 2. Quantiles for each variable:
## 
##        2.5%   25%   50%   75% 97.5%
## base 1.1046 1.121 1.129 1.138 1.154
## RR   0.9805 1.003 1.014 1.026 1.048</code></pre>
<p>The baseline relative risk is estimated at 1.105 with limits of the 95% posterior credible interval equal to 1.12 and 1.154.</p>
</div>
<div id="stan" class="section level3 unnumbered hasAnchor">
<h3>Stan<a href="computation.html#stan" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We now run the same example in Stan.</p>
<p>Load <code>stan package</code> with options</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r foldable"><code class="sourceCode r"><span id="cb155-1"><a href="computation.html#cb155-1" tabindex="-1"></a><span class="fu">library</span>(rstan)</span>
<span id="cb155-2"><a href="computation.html#cb155-2" tabindex="-1"></a></span>
<span id="cb155-3"><a href="computation.html#cb155-3" tabindex="-1"></a><span class="fu">options</span>(<span class="at">mc.cores =</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>())</span>
<span id="cb155-4"><a href="computation.html#cb155-4" tabindex="-1"></a><span class="fu">rstan_options</span>(<span class="at">auto_write =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>data {
  int&lt;lower=0&gt; N;
  vector[N] E; // expected cases?
  vector[N] X1; // what are these covariates?
  vector[N] X2;
  int Y[N] ;
}

parameters {
  real beta0;
  real beta1;
  real beta2;
}
transformed parameters{
  real base = exp(beta0);
  real RR = exp(beta1);
}

model {
  vector[N] mu;
  
  for(i in 1:N){
    mu[i] = log(E[i])+ beta0 + beta1*X1[i] + beta2*X2[i];
    Y[i] ~ poisson_log(mu[i]);
  }

  beta0 ~ normal(0 , 100);
  beta1 ~ normal(0 , 100);
  beta2 ~ normal(0 , 100);
  
}</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="computation.html#cb157-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/DataExample53.csv&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb157-2"><a href="computation.html#cb157-2" tabindex="-1"></a></span>
<span id="cb157-3"><a href="computation.html#cb157-3" tabindex="-1"></a>stan_data <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb157-4"><a href="computation.html#cb157-4" tabindex="-1"></a>  <span class="at">N =</span> <span class="fu">nrow</span>(data),</span>
<span id="cb157-5"><a href="computation.html#cb157-5" tabindex="-1"></a>  <span class="at">E =</span> data<span class="sc">$</span>exp_lungc65pls,</span>
<span id="cb157-6"><a href="computation.html#cb157-6" tabindex="-1"></a>  <span class="at">X1 =</span> <span class="fu">as.vector</span>(<span class="fu">scale</span>(data<span class="sc">$</span>k3)),</span>
<span id="cb157-7"><a href="computation.html#cb157-7" tabindex="-1"></a>  <span class="at">X2 =</span> <span class="fu">as.vector</span>(<span class="fu">scale</span>(data<span class="sc">$</span>k2)),</span>
<span id="cb157-8"><a href="computation.html#cb157-8" tabindex="-1"></a>  <span class="at">Y =</span> data<span class="sc">$</span>lungc65pls</span>
<span id="cb157-9"><a href="computation.html#cb157-9" tabindex="-1"></a>)</span>
<span id="cb157-10"><a href="computation.html#cb157-10" tabindex="-1"></a></span>
<span id="cb157-11"><a href="computation.html#cb157-11" tabindex="-1"></a>Example6_3_Stan  <span class="ot">&lt;-</span> <span class="fu">stan</span>(</span>
<span id="cb157-12"><a href="computation.html#cb157-12" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">&quot;functions/Example6_3.stan&quot;</span>,</span>
<span id="cb157-13"><a href="computation.html#cb157-13" tabindex="-1"></a>  <span class="at">data =</span> stan_data,</span>
<span id="cb157-14"><a href="computation.html#cb157-14" tabindex="-1"></a>  <span class="at">warmup =</span> <span class="dv">5000</span>,</span>
<span id="cb157-15"><a href="computation.html#cb157-15" tabindex="-1"></a>  <span class="at">iter =</span> <span class="dv">10000</span>,</span>
<span id="cb157-16"><a href="computation.html#cb157-16" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">3</span>,</span>
<span id="cb157-17"><a href="computation.html#cb157-17" tabindex="-1"></a>  <span class="at">include =</span> <span class="cn">TRUE</span></span>
<span id="cb157-18"><a href="computation.html#cb157-18" tabindex="-1"></a>)</span></code></pre></div>
<p>Checking the traceplots and posterior summaries of the parameters.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="computation.html#cb158-1" tabindex="-1"></a>rstan<span class="sc">::</span><span class="fu">traceplot</span>(Example6_3_Stan,</span>
<span id="cb158-2"><a href="computation.html#cb158-2" tabindex="-1"></a>                 <span class="at">pars =</span> <span class="fu">c</span>(<span class="st">&quot;beta1&quot;</span>, <span class="st">&quot;base&quot;</span>, <span class="st">&quot;RR&quot;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/Ex%206.3%20stan%20traceplots-1.png" width="672" /></p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="computation.html#cb159-1" tabindex="-1"></a>stan_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(Example6_3_Stan, <span class="at">pars =</span> <span class="fu">c</span>(<span class="st">&quot;RR&quot;</span>, <span class="st">&quot;base&quot;</span>))</span>
<span id="cb159-2"><a href="computation.html#cb159-2" tabindex="-1"></a>stan_summary<span class="sc">$</span>summary</span></code></pre></div>
<pre><code>##          mean      se_mean         sd      2.5%      25%      50%      75%
## RR   1.014958 0.0002226978 0.01751280 0.9808189 1.003024 1.015022 1.026792
## base 1.128715 0.0001341104 0.01258458 1.1044455 1.120106 1.128723 1.137275
##         97.5%    n_eff      Rhat
## RR   1.049442 6184.139 1.0000989
## base 1.153651 8805.473 0.9998812</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="embracing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Strategies.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/06-Chpt6.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
